### ISSUE TITLE
Eliixir LS slow since upgrading to elixir 1.11

### ISSUE THREAD

**Issue by reneweteling** [elixir-lsp/elixir-ls#385] opened 2020-10-13 06:13 UTC
Hiya,

Ever since ive upgraded to Elixir 1.11, elixir ls has become quite slow, formatting a file, even if the changes are just some spaces can take over 30 sec.

### Environment

* Elixir & Erlang versions (elixir --version): 
`Erlang/OTP 23 [erts-11.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]`
`Elixir 1.11.0 (compiled with Erlang/OTP 23)`
* Operating system: `MacOS 10.15.7`
* Editor or IDE name (e.g. Emacs/VSCode): `VsCode 1.50.0`
* Editor Plugin/LSP Client name: `v.0.6.1`

### ElixirLS logs
```
[Info  - 8:06:51 AM] [ElixirLS Dialyzer] Checking for stale beam files
[Info  - 8:06:51 AM] [ElixirLS WorkspaceSymbols] Updating index...
[Info  - 8:07:05 AM] [ElixirLS WorkspaceSymbols] 1 modules need reindexing
[Info  - 8:07:05 AM] [ElixirLS WorkspaceSymbols] 0 callbacks added to index
[Info  - 8:07:05 AM] [ElixirLS WorkspaceSymbols] 1 modules added to index
[Info  - 8:07:05 AM] [ElixirLS WorkspaceSymbols] 0 types added to index
[Info  - 8:07:05 AM] [ElixirLS WorkspaceSymbols] 10 functions added to index
[Info  - 8:07:30 AM] [ElixirLS Dialyzer] Found 2760 changed files in 20172 milliseconds
[Info  - 8:08:24 AM] [ElixirLS Dialyzer] Analysis finished in 314742 milliseconds
```

**Comment by lukaszsamson** [comment] 2020-10-13 06:53
Duplicate of https://github.com/elixir-lsp/elixir-ls/issues/381

**Closed by lukaszsamson** 2020-10-13 06:53 UTC

**Comment by BlueHotDog** [comment] 2020-10-13 11:25
For me, after upgrading to elixir 1.11 + latest extension version, everything became very unstable. have to restart vscode couple of times a day :(

**Comment by lukaszsamson** [comment] 2020-10-13 11:56
> For me, after upgrading to elixir 1.11 + latest extension version, everything became very unstable. have to restart vscode couple of times a day :(

@BlueHotDog Can you provide repro steps. logs or any other info that could help in diagnosing your issues?

**Comment by BlueHotDog** [comment] 2020-10-13 11:57
Hmm, i can try and put something later on, but i think there are already a couple of issues pointing to this
