### ISSUE TITLE
High CPU usage with 0.12.0

### ISSUE THREAD

**Issue by Defman21** [elixir-lsp/elixir-ls#788] opened 2022-12-13 20:41 UTC
### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.1 (compiled with Erlang/OTP 25)
```

* Elixir Language Server version: 0.12.0
* Operating system: MacOS 13.0.1
* Editor or IDE name: VSCode
* Editor Plugin/LSP Client name and version: Elixir-LS 0.12.0

### Current behavior

VSCode starts to feel sluggish, my CPU (MacBook Pro, M1) is at 90C all the time and I receive many unnecessary completions, e.g., for the `Application` token:

<img width="474" alt="image" src="https://user-images.githubusercontent.com/7100645/207438297-bf02bcbf-5624-496d-b7ef-487e17b2e98f.png">

### Expected behavior

Here's how it looks with Elixir LS 0.11.0:

<img width="482" alt="image" src="https://user-images.githubusercontent.com/7100645/207438496-2cf8f336-2d2e-4b82-882b-32333f074e00.png">

My CPU is not melting and I don't receive unnecessary completions.

### Note

For testing this, I compiled both v0.12.0 and v0.11.0 and replaced the bundled elixir-ls in the VSCode extension.

**Comment by lukaszsamson** [comment] 2022-12-19 21:05
Duplicate of https://github.com/elixir-lsp/elixir-ls/issues/772

@Defman21 can you try master? The issue should be fixed already

**Closed by lukaszsamson** 2022-12-19 21:05 UTC
Labels: duplicate

**Comment by Defman21** [comment] 2022-12-19 21:30
master branch is broken for me:

```
[Error - 12:27:21 AM] GenServer ElixirLS.LanguageServer.Experimental.SourceFile.Store terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for %ElixirLS.LanguageServer.Experimental.SourceFile.Document{lines: {{:line, "defmodule REDACTED do", "\n", 1, true}, {:line, "  @moduledoc false", "\n", 2, true}, {:line, "", "\n", 3, true}, {:line, "  use Supervisor", "\n", 4, true}, {:line, "", "\n", 5, true}, {:line, "  def start_link(opts) do", "\n", 6, true}, {:line, "    Supervisor.start_link(__MODULE__, :ok, opts)", "\n", 7, true}, {:line, "  end", "\n", 8, true}, {:line, "", "\n", 9, true}, {:line, "  @impl Supervisor", "\n", 10, true}, {:line, "  def init(:ok) do", "\n", 11, true}, {:line, "    Applicat", "\n", 12, true}, {:line, "    config = Application.fetch_env!(:music_spit, REDACTED "\n", 13, true}, {:line, "", "\n", 14, true}, {:line, "    children = [", "\n", 15, true}, {:line, "      {Plug.Cowboy,", "\n", 16, true}, {:line, "       scheme: :http, plug: REDACTED options: [port: Keyword.fetch!(config, :port)]},", "\n", 17, true}, {:line, "      REDACTED "\n", 18, true}, {:line, "      REDACTED "\n", 19, true}, {:line, "    ]", "\n", 20, true}, {:line, "", "\n", 21, true}, {:line, "    Supervisor.init(children, strategy: :one_for_one)", "\n", 22, true}, {:line, "  end", "\n", 23, true}, {:line, "end", "\n", 24, true}}, starting_index: 1} of type ElixirLS.LanguageServer.Experimental.SourceFile.Document (a struct). This protocol is implemented for the following type(s): Date.Range, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Jason.OrderedObject, List, Map, MapSet, Range, Stream
    (elixir 1.14.1) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.14.1) lib/enum.ex:230: Enumerable.slice/1
    (elixir 1.14.1) lib/enum.ex:4379: Enum.slice_forward/4
    (elixir 1.14.1) lib/enum.ex:468: Enum.at/3
    (language_server 0.12.0) lib/language_server/experimental/source_file/document.ex:36: ElixirLS.LanguageServer.Experimental.SourceFile.Document.fetch_line/2
    (language_server 0.12.0) lib/language_server/experimental/source_file/conversions.ex:73: ElixirLS.LanguageServer.Experimental.SourceFile.Conversions.to_elixir/2
    (language_server 0.12.0) lib/language_server/experimental/source_file/conversions.ex:28: ElixirLS.LanguageServer.Experimental.SourceFile.Conversions.to_elixir/2
    (language_server 0.12.0) lib/language_server/experimental/source_file.ex:138: ElixirLS.LanguageServer.Experimental.SourceFile.apply_change/2
Last message (from ElixirLS.LanguageServer.Experimental.Server): {:update, "file:///Users/defman/Projects/REDACTED", #Function<1.80531545/1 in ElixirLS.LanguageServer.Experimental.Server.State.apply/2>}
State: %ElixirLS.LanguageServer.Experimental.SourceFile.Store.State{source_files: %{"file:///Users/defman/Projects/REDACTED" => %ElixirLS.LanguageServer.Experimental.SourceFile{uri: "file:///Users/defman/Projects/REDACTED", path: "/Users/defman/Projects/REDACTED", version: 10, dirty?: false, document: %ElixirLS.LanguageServer.Experimental.SourceFile.Document{lines: {{:line, "defmodule REDACTED do", "\n", 1, true}, {:line, "  @moduledoc false", "\n", 2, true}, {:line, "", "\n", 3, true}, {:line, "  use Supervisor", "\n", 4, true}, {:line, "", "\n", 5, true}, {:line, "  def start_link(opts) do", "\n", 6, true}, {:line, "    Supervisor.start_link(__MODULE__, :ok, opts)", "\n", 7, true}, {:line, "  end", "\n", 8, true}, {:line, "", "\n", 9, true}, {:line, "  @impl Supervisor", "\n", 10, true}, {:line, "  def init(:ok) do", "\n", 11, true}, {:line, "    Applicat", "\n", 12, true}, {:line, "    config = Application.fetch_env!(:music_spit, REDACTED "\n", 13, true}, {:line, "", "\n", 14, true}, {:line, "    children = [", "\n", 15, true}, {:line, "      {Plug.Cowboy,", "\n", 16, true}, {:line, "       scheme: :http, plug: REDACTED options: [port: Keyword.fetch!(config, :port)]},", "\n", 17, true}, {:line, "      REDACTED "\n", 18, true}, {:line, "      REDACTED "\n", 19, true}, {:line, "    ]", "\n", 20, true}, {:line, "", "\n", 21, true}, {:line, "    Supervisor.init(children, strategy: :one_for_one)", "\n", 22, true}, {:line, "  end", "\n", 23, true}, {:line, "end", "\n", 24, true}}, starting_index: 1}}}}
Client ElixirLS.LanguageServer.Experimental.Server is alive

    (stdlib 4.0.1) gen.erl:256: :gen.do_call/4
    (elixir 1.14.1) lib/gen_server.ex:1035: GenServer.call/3
    (language_server 0.12.0) lib/language_server/experimental/server/state.ex:24: ElixirLS.LanguageServer.Experimental.Server.State.apply/2
    (stdlib 4.0.1) timer.erl:235: :timer.tc/1
    (language_server 0.12.0) lib/language_server/experimental/server.ex:76: ElixirLS.LanguageServer.Experimental.Server.apply_to_state/2
    (language_server 0.12.0) lib/language_server/experimental/server.ex:66: ElixirLS.LanguageServer.Experimental.Server.handle_notification/2
    (language_server 0.12.0) lib/language_server/experimental/server.ex:41: ElixirLS.LanguageServer.Experimental.Server.handle_cast/2
    (stdlib 4.0.1) gen_server.erl:1120: :gen_server.try_dispatch/4
[Warn  - 12:27:21 AM] ** (exit) exited in: GenServer.call(ElixirLS.LanguageServer.JsonRpc, {:packet, %{"id" => 45, "jsonrpc" => "2.0", "method" => "textDocument/documentSymbol", "params" => %{"textDocument" => %{"uri" => "file:///Users/defman/Projects/REDACTED"}}}}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.14.1) lib/gen_server.ex:1027: GenServer.call/3
    (elixir 1.14.1) lib/stream.ex:481: anonymous fn/4 in Stream.each/2
    (elixir 1.14.1) lib/stream.ex:1651: Stream.do_element_resource/6
    (elixir 1.14.1) lib/stream.ex:1811: Enumerable.Stream.do_each/4
    (elixir 1.14.1) lib/stream.ex:689: Stream.run/1
    nofile:1: (file)
    (stdlib 4.0.1) erl_eval.erl:748: :erl_eval.do_apply/7
[Info  - 12:27:25 AM] Connection to server got closed. Server will restart.
```
