### ISSUE TITLE
Frequent Crashes Reported By Elixir LS

### ISSUE THREAD

**Issue by apoorv-2204** [elixir-lsp/elixir-ls#885] opened 2023-05-10 11:12 UTC
https://elixirforum.com/t/frequent-crashes-reported-by-elixir-ls/57038
### Precheck

** There is frequent crashes of elixir ls ,on vscode **
Due to which cant use the features provided by elixir ls.

**The standard debugging measures taken are:**
- enable ,disable , install , uninstall , elixir ls extension
- restart vs code
- delete .elixir_ls, _build
- mix deps.get , mix dep.compile. mix deps.clean,etc

```
an exception was raised:
    ** (UndefinedFunctionError) function Proxy.Mixfile.project/0 is undefined (module Proxy.Mixfile is not available)
        Proxy.Mixfile.project()
        (mix 1.14.1) lib/mix/project.ex:838: Mix.Project.get_project_config/1
        (mix 1.14.1) lib/mix/project.ex:141: Mix.Project.push/3
        (mix 1.14.1) lib/mix/project.ex:785: Mix.Project.load_project/2
        (mix 1.14.1) lib/mix/project.ex:389: Mix.Project.in_project/4
        (elixir 1.14.1) lib/file.ex:1607: File.cd!/2
        (language_server 0.15.1) lib/language_server/build.ex:83: anonymous fn/3 in ElixirLS.LanguageServer.Build.reload_project/0
        (stdlib 4.2) maps.erl:411: :maps.fold_1/3
```

```
an exception was raised:
** (UndefinedFunctionError) function Tzdata.Mixfile.project/0 is undefined (module Tzdata.Mixfile is not available)
Tzdata.Mixfile.project()
(mix 1.14.1) lib/mix/project.ex:838: Mix.Project.get_project_config/1
(mix 1.14.1) lib/mix/project.ex:141: Mix.Project.push/3
(mix 1.14.1) lib/mix/project.ex:785: Mix.Project.load_project/2
(mix 1.14.1) lib/mix/project.ex:389: Mix.Project.in_project/4
(elixir 1.14.1) lib/file.ex:1607: File.cd!/2
(language_server 0.15.1) lib/language_server/build.ex:83: anonymous fn/3 in ElixirLS.LanguageServer.Build.reload_project/0
(stdlib 4.2) maps.erl:411: :maps.fold_1/3ElixirLS

Kernel.defmodule(alias, do_block) view on hexdocs

Defines a module given by name with the given contents.

This macro defines a module with the given alias as its name and with the given contents. It returns a tuple with four elements:

:module
the module name
the binary contents of the module
the result of evaluating the contents block
```

```
** (UndefinedFunctionError) function OpentelemetryLoggerMetadata.MixProject.project/0 is undefined (module OpentelemetryLoggerMetadata.MixProject is not available)
        OpentelemetryLoggerMetadata.MixProject.project()
        (mix 1.14.3) lib/mix/project.ex:838: Mix.Project.get_project_config/1
        (mix 1.14.3) lib/mix/project.ex:141: Mix.Project.push/3
        (mix 1.14.3) lib/mix/project.ex:785: Mix.Project.load_project/2
        (mix 1.14.3) lib/mix/project.ex:389: Mix.Project.in_project/4
        (elixir 1.14.3) lib/file.ex:1607: File.cd!/2
        (language_server 0.14.6) lib/language_server/build.ex:83: anonymous fn/3 in ElixirLS.LanguageServer.Build.reload_project/0
        (stdlib 4.2) maps.erl:411: :maps.fold_1/3
```

### Environment

* Elixir & Erlang versions (elixir --version):  
elixir 1.14.1-otp-25
erlang 25.2.2

* Elixir Language Server version: 
latest extension on vscode
* Operating system: 
 22.04
* Editor or IDE name (e.g. Emacs/VSCode):
 VSCode
* Editor Plugin/LSP Client name and version:

**Comment by lukaszsamson** [comment] 2023-05-10 11:15
Please post a repro steps or a project that reproduces it

**Comment by lukaszsamson** [comment] 2023-05-18 08:13
ping @apoorv-2204

**Comment by lukaszsamson** [comment] 2023-07-13 11:18
A minimal repo and repro steps will do

**Comment by APB9785** [comment] 2023-07-21 15:24
I've had this issue on every single repo I've ever used ElixirLS with.

**Comment by lukaszsamson** [comment] 2023-07-21 15:45
> Even a brand new project with mix phx.new will reproduce this issue consistently.

@APB9785 works for me, no crashes
<img width="1473" alt="Screenshot 2023-07-21 at 17 38 41" src="https://github.com/elixir-lsp/elixir-ls/assets/1078186/6f85a1dc-9485-411f-b6f0-32ec59cef3e4">

Fill out the bug template. Provide versions and detailed repro steps. Otherwise feel free to clone the repo and create a PR with a failing test

**Comment by apoorv-2204** [comment] 2023-07-21 16:01
![image](https://github.com/elixir-lsp/elixir-ls/assets/90304197/bd602724-13c8-464f-989e-9ea52de051fc)

**Comment by lukaszsamson** [comment] 2023-07-21 16:04
> ![image](https://user-images.githubusercontent.com/90304197/255224867-bd602724-13c8-464f-989e-9ea52de051fc.png)

@apoorv-2204 That's not a bug. Please install OTP with doc chunks or build from source with correct flags.

**Comment by apoorv-2204** [comment] 2023-07-21 16:25
```an exception was raised:
    ** (File.Error) could not set current working directory to "/home/apoorv-2204/Documents/aenode/deps/inet_cidr": no such file or directory
        (elixir 1.14.1) lib/file.ex:1580: File.cd!/1
        (elixir 1.14.1) lib/file.ex:1604: File.cd!/2
        (language_server 0.15.1) lib/language_server/build.ex:83: anonymous fn/3 in ElixirLS.LanguageServer.Build.reload_project/0
        (stdlib 4.1.1) maps.erl:411: :maps.fold_1/3
        (language_server 0.15.1) lib/language_server/build.ex:81: ElixirLS.LanguageServer.Build.reload_project/0
        (language_server 0.15.1) lib/language_server/build.ex:20: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3
        (stdlib 4.1.1) timer.erl:235: :timer.tc/1
        (language_server 0.15.1) lib/language_server/build.ex:14: anonymous fn/3 in ElixirLS.LanguageServer.Build.build/3```

**Comment by lukaszsamson** [comment] 2023-07-21 16:54
@apoorv-2204 Did you delete deps directory while ElixirLS is building?

This is not getting anywhere. Either post a concrete repro steps or I'm closing that

**Comment by apoorv-2204** [comment] 2023-07-21 17:38
Yes I did several times

**Comment by lukaszsamson** [comment] 2023-07-21 21:15
A crash is expected in that situation

**Comment by lukaszsamson** [comment] 2023-07-22 07:34
We can add a try/rescue in that call but don't expect software to work if you delete files it's trying to read. If you delete deps during mix compile it will crash as well.

**Closed** 2023-08-08 06:11 UTC
Labels: waiting for information
