### ISSUE TITLE
"Go to definition" does not work with macros

### ISSUE THREAD

**Issue by Sleepful** [elixir-lsp/elixir-ls#767] opened 2022-11-10 07:08 UTC
### Environment

* Elixir & Erlang versions (elixir --version): 
Erlang/OTP 25 [erts-13.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.14.1 (compiled with Erlang/OTP 25)

* Elixir Language Server version: elixir-ls-14
* Operating system: OSX
* Editor or IDE name (e.g. Emacs/VSCode): emacs
* Editor Plugin/LSP Client name and version: LSP

### Current behavior

`lsp-find-definition` does not work on macros

### Expected behavior

`lsp-find-definition` should work on macros

**Comment by lukaszsamson** [comment] 2022-11-10 08:02
Please post a project that reproduces it

**Comment by robsonpeixoto** [comment] 2022-11-25 21:48
https://github.com/robsonpeixoto/elixir-ls-go-to-definition-bug

Open the file https://github.com/robsonpeixoto/elixir-ls-go-to-definition-bug/blob/main/lib/bug.ex and try to `go-to-defition` of `ModA.say_hi` function.

**Comment by lukaszsamson** [comment] 2022-11-26 14:00
I cannot reproduce it when building elixir-ls locally

<img width="1128" alt="Screenshot 2022-11-26 at 14 35 27" src="https://user-images.githubusercontent.com/1078186/204091572-4af64566-0ff7-453b-83a7-9c5df9748dbd.png">
```
[Info  - 2:33:44 PM] Started ElixirLS v0.12.0
[Info  - 2:33:44 PM] ElixirLS built with elixir "1.14.2" on OTP "25"
[Info  - 2:33:44 PM] Running on elixir "1.14.2 (compiled with Erlang/OTP 25)" on OTP "25"
```

but I can when I run it in installed plugin
```
[Info  - 2:36:55 PM] Started ElixirLS v0.12.0
[Info  - 2:36:55 PM] ElixirLS built with elixir "1.11.4" on OTP "22"
[Info  - 2:36:55 PM] Running on elixir "1.14.2 (compiled with Erlang/OTP 25)" on OTP "25"
```
It's a duplicate of https://github.com/elixir-lsp/elixir-ls/issues/193

**Closed by lukaszsamson** 2022-11-26 14:00 UTC

**Comment by Sleepful** [comment] 2022-12-10 04:34
@lukaszsamson the linked issue mentions that the problem comes from building elixir-ls with an elixir version different from system version. But I have the `elixir-ls-1.14-25.1` and `Elixir 1.14.1`, are these not the same version?

I downloaded directly from the Relase page here in github, not the VSCode marketplace or whatever.

oh but when I look into the version of the LSP: `ElixirLS compiled with Elixir 1.11.4`

so why is `elixir-ls-1.14-25.1` compiled with `Elixir 1.11.4`?

**Comment by Sleepful** [comment] 2022-12-10 18:50
So apparently there was a lingering ElixirLS version that was taking precedence over the latest one. I ended up building from source. Came across this issue, and this solved it: https://github.com/elixir-lsp/elixir-ls/issues/783#issuecomment-1338926724

Can confirm I can follow macros now.
