### ISSUE TITLE
Callback info about the 'Elixir.Mix.Task' behaviour is not available

### ISSUE THREAD

**Issue by Ajwah** [elixir-lsp/elixir-ls#117] opened 2020-02-09 18:36 UTC
### Environment

* Elixir & Erlang versions (elixir --version): latest
* Operating system: macos
* Client (editor or IDE): vscode

### Sanity Check List
1.  Create a new Mix project with `mix new empty`, then open that project with VS Code and open an Elixir file. Is your issue reproducible on the empty project? YES
3.  Check the output log by opening `View > Output` and selecting "ElixirLS" in the dropdown. Please include any output that looks relevant. (If ElixirLS isn't in the dropdown, the server failed to launch.)
```
13:14:18.445 [error] Process #PID<0.15210.0> raised an exception
** (SyntaxError) nofile:11: syntax error before: 'Callback'
    (language_server) lib/language_server/providers/document_symbols.ex:41: ElixirLS.LanguageServer.Providers.DocumentSymbols.list_symbols/1
    (language_server) lib/language_server/providers/document_symbols.ex:35: ElixirLS.LanguageServer.Providers.DocumentSymbols.symbols/2
    (language_server) lib/language_server/server.ex:442: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
```
4.  Check the developer console by opening `Help > Toggle Developer Tools` and include any errors that look relevant.
Nothing relevant.

### Comments
Based on the [documentation for dialyzer](http://erlang.org/doc/man/dialyzer.html), I believe that starting `dialyzer` with the option: `--apps mix` would resolve this matter. When I go to settings however, I am only able to provide `warn options`. 

If my assessment is correct, could someone kindly share with me how I could customize the starting options for dialyzer manually for the time being?

**Comment by axelson** [comment] 2020-02-09 19:31
I'm unable to reproduce your issue by just opening the `empty.ex` or `mix.exs` file. Are you taking some other action after opening those files?

**Comment by Ajwah** [comment] 2020-02-11 17:51
Kindly open following in VSCode: https://github.com/Ajwah/dummy_task.

You should see:
<img width="844" alt="Screen Shot 2020-02-11 at 12 50 53 PM" src="https://user-images.githubusercontent.com/11848116/74263608-28847f00-4ccd-11ea-819a-6530ab1f6992.png">

**Comment by axelson** [comment] 2020-02-12 17:15
Okay, I see. It looks like that error occurs if you run dialyzer in the project directly as well. The fix is to add `dialyzer: [plt_add_apps: [:mix]]` to the `project/0` definition in your `mix.exs`: https://stackoverflow.com/a/51218081/

After adding that the error should go away.

**Comment by Ajwah** [comment] 2020-02-12 18:19
In the project I shared, dialyzer is not included. I tried before adding: `dialyzer: [plt_add_apps: [:mix]]` to `mix.exs` but that did not help either.



What about:
> Based on the [documentation for dialyzer](http://erlang.org/doc/man/dialyzer.html), I believe that starting `dialyzer` with the option: `--apps mix` would resolve this matter. When I go to settings however, I am only able to provide `warn options`. 
If my assessment is correct, could someone kindly share with me how I could customize the starting options for dialyzer manually for the time being?

**Comment by axelson** [comment] 2020-02-13 17:44
Oh, I see. I don't think there's currently a work-around without adding dialyxir to your project, but we can work on adding a new configuration option to the extension.

**Comment by lukaszsamson** [comment] 2020-09-30 16:28
@axelson Let's add a note in the readme about a workaround

**Comment by lukaszsamson** [comment] 2020-11-25 18:58
No longer reproducible, most likely fixed in https://github.com/elixir-lsp/elixir-ls/pull/225/commits/f5d441390af178c82f4fe2b2a49f8455523301e8

**Closed by lukaszsamson** 2020-11-25 18:58 UTC
