### ISSUE TITLE
Adding too many newlines when format

### ISSUE THREAD

**Issue by grhamm-pabst** [elixir-lsp/elixir-ls#510] opened 2021-03-11 04:48 UTC
When I format an .ex file the ElixirLS adds newlines above the first function of the module:
![image](https://user-images.githubusercontent.com/48564739/110736958-4c393200-820b-11eb-86ab-63fe5233cd7c.png)

In the main module file it appears to be working properly in all projects I tested.

It keeps adding new lines when I format over and over.

**Comment by grhamm-pabst** [comment] 2021-03-11 04:51
I talked to some people in a elixir community and seems like a frequent problem

**Comment by Ovyerus** [comment] 2021-03-11 08:19
I've been getting this too a couple times. Turning on render whitespaces in these instances has showed `CRLF` line endings instead of Unix `LF` endings weirdly, considering I have vscode set to only do LF. Manually changing the line ending back to `LF` has fixed it in the instances I've had it occur. Still very annoying.

**Comment by lukaszsamson** [comment] 2021-03-11 09:16
@grhamm-pabst since you didn't post your client versions and OS I assume it's a duplicate of https://github.com/elixir-lsp/elixir-ls/issues/484. Next time please use the search function before opening an issue and fill the template

**Closed by lukaszsamson** 2021-03-11 09:16 UTC
