### ISSUE TITLE
Feature: add support to peek definition of defdelegated code

### ISSUE THREAD

**Issue by wanton7** [elixir-lsp/elixir-ls#132] opened 2020-02-18 09:53 UTC
### Environment
Erlang/OTP 21 [erts-10.3] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Elixir 1.10.1 (compiled with Erlang/OTP 21)
Visual Studio Code 1.42.1
Windows 10
ElixirLS Fork: Elixir support and debugger 0.3.0

### Current behavior
Currently peek definition (Alt+F12) will peek into defdelegate not to code it points to. It's very annoying that if you want use defdelegate you'll lose ability to peek actual code.

### Feature behavior
Peek definition (Alt+F12) would show code defdelegate points to instead.
This could be under settings to be enabled if not wanted to made enabled by default.

**Comment by lukaszsamson** [comment] 2020-02-18 10:55
Duplicate of https://github.com/elixir-lsp/elixir-ls/issues/126

**Comment by wanton7** [comment] 2020-02-18 12:42
How is this duplicate of #126? That one is navigation from defdelegate to a function. These features are not the same at all.

**Comment by lukaszsamson** [comment] 2020-02-18 21:01
It is. Both use the same provider underneath.

**Comment by axelson** [comment] 2020-02-18 21:35
I would say as written (i.e. from a user perspective) they're not duplicates, even if they're solved in the same commit.

**Comment by wanton7** [comment] 2020-02-18 21:40
Oh would that mean when #126 is completed then everything in VSCode would work like you would be calling function directly when using defdelegate? If so that would be awesome.

**Comment by axelson** [comment] 2020-02-20 17:50
> Oh would that mean when #126 is completed then everything in VSCode would work like you would be calling function directly when using defdelegate? If so that would be awesome.

Minor nit: I don't want to make defdelegate completely transparent, because that would hide the fact that it is indeed a defdelegate, not a normal function definition. But with that said I am reopening this issue because it is not solved by #134 

If it was than than calling `Peek Definition` in VSCode would look the same. But instead we have:
![screenshot-defdelegate](https://user-images.githubusercontent.com/9973/74963274-8bed6b80-53b5-11ea-93ba-0ea18bb05eb1.png)

![screenshot-direct](https://user-images.githubusercontent.com/9973/74963286-90198900-53b5-11ea-80fc-50398b000b61.png)

But instead of making them the same, what we want is for two definitions to be shown in the first case.

**Comment by asummers** [comment] 2020-02-21 01:26
Also unsure if this was tested but consider multiple chained `defdelegate` calls (with no suggestion that this should be done in practice!).

**Comment by lukaszsamson** [comment] 2020-02-22 08:49
@asummers Yes, it was, see https://github.com/elixir-lsp/elixir_sense/blob/9531d0e90652d3baf906ad4553d0d17baf4096f5/test/elixir_sense/definition_test.exs#L190
elixir_sense now recursively follows defdelegate chain, though ATM I'm no longer convinced that it should as it obscures the fact that there is one.

@axelson 
> But instead of making them the same, what we want is for two definitions to be shown in the first case.

I disagree. In your example `myFun` is defined in `MixTaskBug`. What you describe sounds more like you would like to "Peek implementation". For thet to work we would need another server capability and frankly I think we do. It would be useful to be able to navigate to e.g. protocol implementations, behaviour callback impls, overridden functions.

**Comment by axelson** [comment] 2020-02-22 17:27
> I disagree. In your example `myFun` is defined in `MixTaskBug`. What you describe sounds more like you would like to "Peek implementation". For thet to work we would need another server capability and frankly I think we do. It would be useful to be able to navigate to e.g. protocol implementations, behaviour callback impls, overridden functions.

Well `textDocument/definition` does support returning multiple definition locations (result: `Location | Location[] | LocationLink[] | null`) and it seems to work well when multiple results are returned. If used with "Peek Definition" it will show all the definitions (apparently in the order returned by the server):
![screenshot-peek-definition-multiple](https://user-images.githubusercontent.com/9973/75096084-f6321780-553f-11ea-8dae-85fa06a81bda.png)

And then "Go To Definition" works similarly and brings up the same display as "Peek Definitions" and if you press "enter" the last returned result will be navigated to.

So if we change `textDocument/definition` to return all the `defdelegate` locations, along with the final implementation I believe that it will work as expected for users and be very useful. This way we're not hiding the fact that `defdelegate` is used, but we still make the final implementation easy to navigate to.

Although the other option is to utilize `textDocument/implementation` which might be more correct

**Comment by axelson** [comment] 2020-11-27 20:37
This was implemented in #415 and will be released in the next version of ElixirLS. Although it's not exactly as requested because a `defdelegate` is considered an implementation rather than a definition, but I think that makes more sense anyway.

**Closed by axelson** 2020-11-27 20:37 UTC
