### ISSUE TITLE
ElixirLS fails to start with Elixir 1.15 & OTP 26

### ISSUE THREAD

**Issue by sasa1977** [elixir-lsp/elixir-ls#925] opened 2023-06-27 07:22 UTC
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.15 OTP 26
* Elixir Language Server version: 0.15.1
* Operating system: Ubuntu 22.04
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name and version: jakebecker.elixir-ls-0.15.1

### Current behavior

ElixirLS repeatedly crashes on start:

```
Running /home/sasa/.vscode/extensions/jakebecker.elixir-ls-0.15.1/elixir-ls-release/launch.sh
Looking for ASDF install in /home/sasa/.asdf/asdf.sh
ASDF found, relaunching in bash shell
Looking for ASDF install in /home/sasa/.asdf/asdf.sh
Sourcing ASDF
Installing ElixirLS release v0.15.0
Running in /tmp/test
Install complete
[Info  - 9:11:46 AM] Started ElixirLS v0.15.0
[Info  - 9:11:46 AM] Running in /tmp/test
[Info  - 9:11:46 AM] ElixirLS built with elixir "1.15.0" on OTP "26"
[Info  - 9:11:46 AM] Running on elixir "1.15.0 (compiled with Erlang/OTP 26)" on OTP "26"
[Info  - 9:11:46 AM] Protocols are not consolidated
[Info  - 9:11:46 AM] Elixir sources not found (checking in /home/runner/work/elixir/elixir). Code navigation to Elixir modules disabled.
Runtime terminating during boot ({badarg,[{io,put_chars,[standard_error,[_]],[{_},{_},{_}]},{Elixir.Kernel.CLI,exec_fun,2,[{_},{_}]},{Elixir.Kernel.CLI,run,1,[{_},{_}]},{elixir,start_cli,0,[{_},{_}]},{init,start_em,1,[]},{init,do_boot,3,[]}]})
```

**Comment by lukaszsamson** [comment] 2023-06-27 09:31
Duplicate of https://github.com/elixir-lsp/elixir-ls/issues/886. Please wait for OTP 26.0.2 release and next ElixirLS release

**Closed by lukaszsamson** 2023-06-27 09:31 UTC
