### ISSUE TITLE
Single File ElixirLS Alert “No mixfile found in project..."

### ISSUE THREAD

**Issue by andyl** [elixir-lsp/elixir-ls#518] opened 2021-03-28 20:58 UTC
## Background

When editing a single elixir file (an elixir script), ElixirLS gives a warning:

![image](https://user-images.githubusercontent.com/90030/112767840-c587a180-8fcd-11eb-8eb5-d1e12cc13ed8.png)

Elixir 1.12 has a new feature (`Mix.install`) that streamlines the process of writing and sharing single-file Elixir Scripts.  I believe that single-file elixir scripts will be used more frequently, and that it would be good for ElixirLS to support this use case.

This issue is discussed in more detail on the Elixir Forum:

https://elixirforum.com/t/getting-rid-of-elixirls-alert-no-mixfile-found-in-project-to-use-a-subdirectory/38534

## Feature Request

Create a feature that disables ElixirLS for a given file

    - OR -

If a shebang and `Mix.install` is detected, apply ElixirLS to the script and the dependency tree that it generates.

**Comment by axelson** [comment] 2021-03-29 02:56
Hi, thanks for the report! Since `Mix.install` will make this case relatively common I agree that it would be great to include support for this use case. However, there may be a fairly significant amount of work required to get it working because much of the code expects a mix project to exist. One potential approach would be to fallback to a "default" mix project for single-file scripts.

**Comment by lukaszsamson** [comment] 2021-03-29 09:53
Duplicate of https://github.com/elixir-lsp/elixir-ls/issues/307

**Closed by lukaszsamson** 2021-03-29 09:53 UTC
Labels: enhancement

**Comment by axelson** [comment] 2021-03-29 16:41
Ah, I thought there was one but couldn't find it when searching
