### ISSUE TITLE
ElixirLS hangs on save

### ISSUE THREAD

**Issue by jamilabreu** [elixir-lsp/elixir-ls#289] opened 2020-06-06 19:21 UTC
### Environment

* Elixir & Erlang versions (elixir --version):  1.10.3
* Operating system: OSX
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* LSP Client name: 
  * If using VSCode, are you using "ElixirLS: Elixir support and debugger"? Yes

VSCode hangs on save after a while of being fine:

<img width="459" alt="Screenshot 2020-06-06 14 11 55" src="https://user-images.githubusercontent.com/266831/83952779-4db37500-a809-11ea-9f30-0db0126e44e1.png">

Clicking cancel allows the file to save, then same message appears on next save attempt.

**Comment by axelson** [comment] 2020-06-08 06:48
Are you able to reproduce this reliably? I've seen the same myself but having a concrete list of reproduction steps would be very helpful.

**Comment by jamilabreu** [comment] 2020-06-13 16:11
Haven't been able to - seems to be random? But I get it at least once an hour which is frustrating 😢

**Comment by pjo336** [comment] 2020-06-19 03:13
I get this after a couple hours of use, and generally have to restart vs code and things work normally. Really frustrating and wish i could reproduce on a consistent basis. Any logs I can look at to try to provide more context on whatever the messed up state is?

**Comment by axelson** [comment] 2020-06-21 16:58
@pjo336 here's the debugging instructions for vscode: https://github.com/elixir-lsp/vscode-elixir-ls#debugging

**Comment by mattbaker** [comment] 2020-10-20 21:59
Same as https://github.com/elixir-lsp/elixir-ls/issues/381?

**Comment by axelson** [comment] 2020-10-23 16:40
@mattbaker I think this one is different, if related because it fails to format, rather than just being slow.

**Comment by lukaszsamson** [comment] 2021-05-25 06:49
Closing, unable to reproduce

**Closed by lukaszsamson** 2021-05-25 06:49 UTC
Labels: bug, waiting for information
