### ISSUE TITLE
Language server crashes with: undefined function config/4

### ISSUE THREAD

**Issue by hg-runs** [elixir-lsp/elixir-ls#799] opened 2023-01-11 16:05 UTC
### Environment

* Elixir & Erlang versions (elixir --version):  **1.14.1 (compiled with Erlang/OTP 25)" on OTP "25"**
* Elixir Language Server version:  **0.13.0**
* Operating system:  **Windows 8.1**
* Editor or IDE name (e.g. Emacs/VSCode):  **VSCode**

### Current behavior

The language server crashes randomly since about 2-3 months

```
[Info  - 4:14:24 PM] Connection to server got closed. Server will restart.
[Info  - 4:14:25 PM] Started ElixirLS v0.13.0
[Info  - 4:14:25 PM] ElixirLS built with elixir "1.12.3" on OTP "22"
[Info  - 4:14:25 PM] Running on elixir "1.14.1 (compiled with Erlang/OTP 25)" on OTP "25"
[Info  - 4:14:25 PM] Elixir sources not found (checking in p:/home/runner/work/elixir/elixir). Code navigation to Elixir modules disabled.
[Info  - 4:14:30 PM] DETS databases will be rebuilt
[Error - 4:14:31 PM] GenServer ElixirLS.LanguageServer.Server terminating
** (CompileError) config/test.exs:11: undefined function config/4 (there is no such import)
    (elixir 1.14.1) src/elixir_expand.erl:536: :elixir_expand.expand_block/5
    (elixir 1.14.1) src/elixir_expand.erl:40: :elixir_expand.expand/3
    p:/Phoenix/phoenix/installer/backend/config/config.exs:162: (file)
    (elixir 1.14.1) src/elixir.erl:364: :elixir.quoted_to_erl/3
    (elixir 1.14.1) src/elixir.erl:274: :elixir.eval_forms/3
    (elixir 1.14.1) lib/module/parallel_checker.ex:107: Module.ParallelChecker.verify/1
    (elixir 1.14.1) lib/code.ex:422: Code.validated_eval_string/3
Last message: {:"$gen_cast", {:receive_packet, %{"jsonrpc" => "2.0", "me`
```

The relevant line from  `config/test.exs:11:`

> `config :backend, Backend.Repo,  Oban, testing: :inline,`

The relevant line from `p:/Phoenix/phoenix/installer/backend/config/config.exs:162: (file)`

> `import_config "#{config_env()}.exs"`

### Expected behavior

The language server should not crash regardless of the project source files.

If further information is needed, please let me know

**Comment by lukaszsamson** [comment] 2023-01-20 22:51
@hg-runs Please post a repo that reproduces this problem

**Comment by lukaszsamson** [comment] 2023-03-18 09:46
Closing due to lack of info

**Closed by lukaszsamson** 2023-03-18 09:46 UTC
Labels: waiting for information
