### ISSUE TITLE
Hover doesn't work on functions that are not fully qualified

### ISSUE THREAD

**Issue by natrys** [elixir-lsp/elixir-ls#673] opened 2022-02-07 20:03 UTC
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.13.2 (compiled with Erlang/OTP 24)
* Elixir Language Server version: git HEAD
* Operating system: Linux
* Editor or IDE name (e.g. Emacs/VSCode): neovim/VSCode
* Editor Plugin/LSP Client name and version:

### Current behavior

When I hover on a function name that's not fully qualified (and its module already imported before) the function is being interpreted as "Elixir.function" instead of "CorrectModule.function" and as such documentation lookup fails. This happens for both project local and 3rd party library symbols.

![screenshot](https://user-images.githubusercontent.com/32647404/152862213-0cce4eaa-87e7-4121-9eab-dc969b1d4a45.png)

ElixirLS log:

```
Started ElixirLS v0.9.0
Elixir version: "1.13.2 (compiled with Erlang/OTP 24)"
Erlang version: "24"
ElixirLS compiled with Elixir 1.13.2 and erlang 24
MIX_ENV: test
MIX_TARGET: 
[Info  - 01:46:31] Compile took 517 milliseconds
[Info  - 01:46:31] [ElixirLS WorkspaceSymbols] Indexing...
[Info  - 01:46:31] [ElixirLS Dialyzer] Checking for stale beam files
[Info  - 01:46:31] [ElixirLS Dialyzer] Found 1 changed files in 2 milliseconds
[Info  - 01:46:31] [ElixirLS Dialyzer] Analyzing 0 modules: []
[Info  - 01:46:31] [ElixirLS Dialyzer] Analysis finished in 23 milliseconds
[Info  - 01:46:31] Dialyzer analysis is up to date
[Info  - 01:46:31] [ElixirLS WorkspaceSymbols] Module discovery complete
[Info  - 01:46:32] [ElixirLS WorkspaceSymbols] 23 callbacks added to index
[Info  - 01:46:32] [ElixirLS WorkspaceSymbols] 194 modules added to index
[Info  - 01:46:32] [ElixirLS Dialyzer] Writing manifest...
[Info  - 01:46:33] [ElixirLS Dialyzer] Done writing manifest in 1159 milliseconds.
[Info  - 01:46:33] [ElixirLS WorkspaceSymbols] 334 types added to index
[Info  - 01:46:40] [ElixirLS WorkspaceSymbols] 4173 functions added to index
[Error - 01:47:06] Request textDocument/hover failed.
  Message: an exception was raised:
    ** (UndefinedFunctionError) function :"Elixir.hello".__info__/1 is undefined (module :"Elixir.hello" is not available)
        :"Elixir.hello".__info__(:compile)
        (language_server 0.9.0) lib/language_server/providers/hover.ex:149: ElixirLS.LanguageServer.Providers.Hover.source/1
        (language_server 0.9.0) lib/language_server/providers/hover.ex:134: ElixirLS.LanguageServer.Providers.Hover.dep_name/2
        (language_server 0.9.0) lib/language_server/providers/hover.ex:92: ElixirLS.LanguageServer.Providers.Hover.hexdocs_link/3
        (language_server 0.9.0) lib/language_server/providers/hover.ex:72: ElixirLS.LanguageServer.Providers.Hover.add_hexdocs_link/3
        (language_server 0.9.0) lib/language_server/providers/hover.ex:65: ElixirLS.LanguageServer.Providers.Hover.contents/3
        (language_server 0.9.0) lib/language_server/providers/hover.ex:29: ElixirLS.LanguageServer.Providers.Hover.hover/4
        (language_server 0.9.0) lib/language_server/server.ex:783: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
  Code: -32000 

01:47:06.431 [error] Process #PID<0.172.0> raised an exception
** (UndefinedFunctionError) function :"Elixir.hello".__info__/1 is undefined (module :"Elixir.hello" is not available)
    :"Elixir.hello".__info__(:compile)
    (language_server 0.9.0) lib/language_server/providers/hover.ex:149: ElixirLS.LanguageServer.Providers.Hover.source/1
    (language_server 0.9.0) lib/language_server/providers/hover.ex:134: ElixirLS.LanguageServer.Providers.Hover.dep_name/2
    (language_server 0.9.0) lib/language_server/providers/hover.ex:92: ElixirLS.LanguageServer.Providers.Hover.hexdocs_link/3
    (language_server 0.9.0) lib/language_server/providers/hover.ex:72: ElixirLS.LanguageServer.Providers.Hover.add_hexdocs_link/3
    (language_server 0.9.0) lib/language_server/providers/hover.ex:65: ElixirLS.LanguageServer.Providers.Hover.contents/3
    (language_server 0.9.0) lib/language_server/providers/hover.ex:29: ElixirLS.LanguageServer.Providers.Hover.hover/4
    (language_server 0.9.0) lib/language_server/server.ex:783: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
```

### Expected behavior

This seems to be happening since this commit: https://github.com/elixir-lsp/elixir-ls/commit/2e7ac6d5ff555a62e9acba4067382dd07e398f17

Before that, it worked as expected.

**Comment by lukaszsamson** [comment] 2022-02-07 21:24
@zhenfeng-zhu can you take a look?

**Comment by zhenfeng-zhu** [comment] 2022-02-09 02:59
I found the cause of this bug，let me fix it.

**Comment by lukaszsamson** [comment] 2022-02-11 11:12
Addressed in https://github.com/elixir-lsp/elixir-ls/pull/674

**Closed by lukaszsamson** 2022-02-11 11:12 UTC
