### ISSUE TITLE
Language server stops working due to UndefinedFunctionError in supported Elixir/Erlang version

### ISSUE THREAD

**Issue by sashaafm** [elixir-lsp/elixir-ls#708] opened 2022-07-01 09:39 UTC
### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 25 [erts-13.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Elixir 1.13.4 (compiled with Erlang/OTP 24)
```
* Elixir Language Server version: `0.10.0`
* Operating system: 
on a Mac M1
```
ProductName:    macOS
ProductVersion: 12.4
BuildVersion:   21F79
```
* Editor or IDE name (e.g. Emacs/VSCode): `VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 28 2022 12:44:46)`
* Editor Plugin/LSP Client name and version: latest CoC?

### Current behavior

The language server stopped working, I believe, after upgrading the Elixir/OTP (not entirely sure). The server fails 5 times and restarts.

Output from `:CocOpenLog`
```
2022-06-30T16:15:20.715 INFO (pid:34657) [services] - registered service "languageserver.elixirLS"
2022-06-30T16:15:20.716 INFO (pid:34657) [services] - registered service "languageserver.elmLS"
2022-06-30T16:15:20.717 INFO (pid:34657) [plugin] - coc.nvim initialized with node: v18.4.0 after 30ms
2022-06-30T16:15:23.068 INFO (pid:34657) [services] - elixirLS state change: stopped => starting
2022-06-30T16:15:23.072 INFO (pid:34657) [services] - registered service "elixir"
2022-06-30T16:15:23.072 INFO (pid:34657) [services] - elixir state change: stopped => starting
2022-06-30T16:15:23.076 INFO (pid:34657) [language-client-index] - Language server "languageserver.elixirLS" started with 34698
2022-06-30T16:15:23.080 INFO (pid:34657) [language-client-index] - Language server "elixir" started with 34703
2022-06-30T16:15:23.564 INFO (pid:34657) [services] - elixir state change: starting => stopped
2022-06-30T16:15:23.565 INFO (pid:34657) [services] - elixir state change: stopped => starting
2022-06-30T16:15:23.566 INFO (pid:34657) [language-client-index] - Language server "elixir" started with 34761
2022-06-30T16:15:23.701 INFO (pid:34657) [services] - elixirLS state change: starting => running
2022-06-30T16:15:23.703 INFO (pid:34657) [services] - service languageserver.elixirLS started
2022-06-30T16:15:23.856 INFO (pid:34657) [services] - elixir state change: starting => stopped
2022-06-30T16:15:23.856 INFO (pid:34657) [services] - elixir state change: stopped => starting
2022-06-30T16:15:23.857 INFO (pid:34657) [language-client-index] - Language server "elixir" started with 34792
2022-06-30T16:15:24.152 INFO (pid:34657) [services] - elixir state change: starting => stopped
2022-06-30T16:15:24.152 INFO (pid:34657) [services] - elixir state change: stopped => starting
2022-06-30T16:15:24.153 INFO (pid:34657) [language-client-index] - Language server "elixir" started with 34823
2022-06-30T16:15:24.411 INFO (pid:34657) [services] - elixir state change: starting => stopped
2022-06-30T16:15:24.411 ERROR (pid:34657) [services] - Server elixir failed to start: Error: Connection to server got closed. Server will not be restarted.
    at Jf.handleConnectionClosed (/Users/sashaafm/.vim/plugged/coc.nvim/build/index.js:234:1006)
    at Jf.handleConnectionClosed (/Users/sashaafm/.vim/plugged/coc.nvim/build/index.js:234:28588)
    at t (/Users/sashaafm/.vim/plugged/coc.nvim/build/index.js:234:386)
    at xN.invoke (/Users/sashaafm/.vim/plugged/coc.nvim/build/index.js:36:9670)
    at Bd.fire (/Users/sashaafm/.vim/plugged/coc.nvim/build/index.js:36:10436)
    at xi (/Users/sashaafm/.vim/plugged/coc.nvim/build/index.js:37:10897)
    at xN.invoke (/Users/sashaafm/.vim/plugged/coc.nvim/build/index.js:36:9670)
    at Bd.fire (/Users/sashaafm/.vim/plugged/coc.nvim/build/index.js:36:10436)
    at OS.fireClose (/Users/sashaafm/.vim/plugged/coc.nvim/build/index.js:37:525)
    at Socket.<anonymous> (/Users/sashaafm/.vim/plugged/coc.nvim/build/index.js:37:1307)
2022-06-30T16:15:31.247 INFO (pid:34657) [attach] - receive notification: showInfo []
2022-06-30T16:15:52.420 INFO (pid:34657) [attach] - Request action: fillDiagnostics [ 3 ]
2022-06-30T16:15:52.420 ERROR (pid:34657) [attach] - Request error: fillDiagnostics [ 3 ] Error: buffer 3 not attached.
    at lte.setLocationlist (/Users/sashaafm/.vim/plugged/coc.nvim/build/index.js:277:11993)
    at /Users/sashaafm/.vim/plugged/coc.nvim/build/index.js:301:9568
    at Cx.cocAction (/Users/sashaafm/.vim/plugged/coc.nvim/build/index.js:301:17556)
    at HM.<anonymous> (/Users/sashaafm/.vim/plugged/coc.nvim/build/index.js:301:19636)
    at HM.emit (node:events:537:28)
    at HM.handleRequest (/Users/sashaafm/.vim/plugged/coc.nvim/build/index.js:35:2694)
    at AM.emit (node:events:537:28)
    at LM.<anonymous> (/Users/sashaafm/.vim/plugged/coc.nvim/build/index.js:33:1809)
    at LM.emit (node:events:537:28)
    at LM.parseData (/Users/sashaafm/.vim/plugged/coc.nvim/build/index.js:32:5755)
2022-06-30T16:16:00.994 INFO (pid:34657) [attach] - receive notification: openLog []
```

Output from `:CocCommand workspace.showOutput`

```
** (UndefinedFunctionError) function ElixirLS.Utils.OutputDevice.get_opts/0 is undefined (module ElixirLS.Utils.OutputDevice is not available)
    ElixirLS.Utils.OutputDevice.get_opts()
    lib/wire_protocol.ex:33: ElixirLS.Utils.WireProtocol.intercept_output/2
    lib/language_server/cli.ex:6: ElixirLS.LanguageServer.CLI.main/0
    (stdlib 4.0.1) erl_eval.erl:744: :erl_eval.do_apply/7
    (elixir 1.13.4) lib/code.ex:404: Code.validated_eval_string/3
[Error  - 10:17:53] /Users/sashaafm/.config/coc/extensions/node_modules/coc-elixir/els-release/language_server.sh exited with code: 1
[Info  - 10:17:53] Connection to server got closed. Server will restart.
** (UndefinedFunctionError) function ElixirLS.Utils.OutputDevice.get_opts/0 is undefined (module ElixirLS.Utils.OutputDevice is not available)
    ElixirLS.Utils.OutputDevice.get_opts()
    lib/wire_protocol.ex:33: ElixirLS.Utils.WireProtocol.intercept_output/2
    lib/language_server/cli.ex:6: ElixirLS.LanguageServer.CLI.main/0
    (stdlib 4.0.1) erl_eval.erl:744: :erl_eval.do_apply/7
    (elixir 1.13.4) lib/code.ex:404: Code.validated_eval_string/3
[Error  - 10:17:53] /Users/sashaafm/.config/coc/extensions/node_modules/coc-elixir/els-release/language_server.sh exited with code: 1
[Info  - 10:17:53] Connection to server got closed. Server will restart.
** (UndefinedFunctionError) function ElixirLS.Utils.OutputDevice.get_opts/0 is undefined (module ElixirLS.Utils.OutputDevice is not available)
    ElixirLS.Utils.OutputDevice.get_opts()
    lib/wire_protocol.ex:33: ElixirLS.Utils.WireProtocol.intercept_output/2
    lib/language_server/cli.ex:6: ElixirLS.LanguageServer.CLI.main/0
    (stdlib 4.0.1) erl_eval.erl:744: :erl_eval.do_apply/7
    (elixir 1.13.4) lib/code.ex:404: Code.validated_eval_string/3
[Error  - 10:17:53] /Users/sashaafm/.config/coc/extensions/node_modules/coc-elixir/els-release/language_server.sh exited with code: 1
[Info  - 10:17:53] Connection to server got closed. Server will restart.
** (UndefinedFunctionError) function ElixirLS.Utils.OutputDevice.get_opts/0 is undefined (module ElixirLS.Utils.OutputDevice is not available)
    ElixirLS.Utils.OutputDevice.get_opts()
    lib/wire_protocol.ex:33: ElixirLS.Utils.WireProtocol.intercept_output/2
    lib/language_server/cli.ex:6: ElixirLS.LanguageServer.CLI.main/0
    (stdlib 4.0.1) erl_eval.erl:744: :erl_eval.do_apply/7
    (elixir 1.13.4) lib/code.ex:404: Code.validated_eval_string/3
[Error  - 10:17:53] /Users/sashaafm/.config/coc/extensions/node_modules/coc-elixir/els-release/language_server.sh exited with code: 1
[Error  - 10:17:53] Connection to server got closed. Server will not be restarted.
```

### Expected behavior

The language server would not crash and would work as intended.

**Comment by lukaszsamson** [comment] 2022-07-04 07:29
The function from your stacktrace is defined https://github.com/elixir-lsp/elixir-ls/blob/5fe75badaac26297afe6d9a9610f08e07cc40df7/apps/elixir_ls_utils/lib/output_device.ex#L31. The test suite passes and I'm unable to reproduce it with vscode (tested on Intel and M1 mac). I'm going to close this as It looks like a problem with your installation or CoC.

**Closed by lukaszsamson** 2022-07-04 07:29 UTC
