### ISSUE TITLE
"No Mixfile found in project" when building script with Mix.install/2

### ISSUE THREAD

**Issue by greenherringtesting** [elixir-lsp/elixir-ls#553] opened 2021-05-30 14:59 UTC
Elixir 1.12 / OTP 24

When creating a new .exs project using Mix.install instead of a standard mix project, ElixirLS shows an error "No mixfile found in project"

With the new ability to load dependencies in the exs file itself, Elixir LS should be able to detect dependencies included in the script

**Comment by lukaszsamson** [comment] 2021-05-30 17:42
Duplicate of https://github.com/elixir-lsp/elixir-ls/issues/307

**Closed by lukaszsamson** 2021-05-30 17:42 UTC
Labels: duplicate
