### ISSUE TITLE
textDocument/formatting does not support subdirectories in .formatter.exs

### ISSUE THREAD

**Issue by wingyplus** [elixir-lsp/elixir-ls#361] opened 2020-09-01 14:47 UTC
### Environment

* Elixir & Erlang versions (elixir --version): 1.10.4
* Operating system: macOS
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name: ElixirLS

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

If you're experiencing high CPU usage, it is most likely Dialyzer building the PLTs; after it's done the CPU usage should go back to normal. You could also disable Dialyzer in the settings.

### Reproduce step

1. Generate phoenix project with `mix phx.new phoenix_ecto_formatter`
2. Generate migration script with `mix ecto.gen.migration add_simple_table`
3. Edit `./priv/repo/migrations/20200901140512_add_simple_table.exs` which generated by step 2 below:

```elixir
defmodule PhoenixEctoFormatter.Repo.Migrations.AddSimpleTable do
  use Ecto.Migration

  def change do
    create table(:friends) do
        add :name,  :string
    end
  end
end
```
4. Run format document 

### Expected result

The migration script should be formatted

### Actual result

The migration script didn't get format.

### LSP Trace

Captured LSP Trace from the output in VSCode:

```
[Trace - 9:41:25 PM] Sending request 'textDocument/formatting - (17)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/thanabodee/src/github.com/wingyplus/phoenix_ecto_formatter/priv/repo/migrations/20200901140512_add_simple_table.exs"
    },
    "options": {
        "tabSize": 2,
        "insertSpaces": true
    }
}


[Trace - 9:41:25 PM] Received response 'textDocument/formatting - (17)' in 4ms.
Result: []
```

### My .formatter.exs

In the root project: 

```elixir
[
  import_deps: [:ecto, :phoenix],
  inputs: ["*.{ex,exs}", "priv/*/seeds.exs", "{config,lib,test}/**/*.{ex,exs}"],
  subdirectories: ["priv/*/migrations"]
]
```

And in `priv/repo/migrations`:

```elixir
[
  import_deps: [:ecto_sql],
  inputs: ["*.exs"]
]
```

**Comment by wingyplus** [comment] 2020-09-01 15:13
The `ElixirLS.LanguageServer.SourceFile.formatter_opts` returns formatter opts from `priv/repo/migrations/.formatter.exs` and `should_format?` returns false because it doesn't match any globs in the list.

**Comment by lukaszsamson** [comment] 2022-07-05 05:35
The issue is no longer reproducible. Fixed by https://github.com/elixir-lsp/elixir-ls/pull/609

**Closed by lukaszsamson** 2022-07-05 05:35 UTC
Labels: bug, work in progress
