### ISSUE TITLE
ElixirLS keeps compiling project, likely because of yaws dependency

### ISSUE THREAD

**Issue by Awlexus** [elixir-lsp/elixir-ls#578] opened 2021-07-28 11:52 UTC
I have this problem where ElixirLS compiles the project over and over again, just after compiling the project. When I started a script to see if there are any changes to the file system, it always pointed out that a [file in yaws has been written](https://github.com/erlyaws/yaws/blob/master/rebar.config.script#L24-L31), in sync with the compilation of the project. 

Disclaimer: I haven't checked in code whether this could be the root cause.  

### Environment

* Editor or IDE name: VSCode 
* Editor Plugin/LSP Client name: ElixirLS

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor
  * NOTE: This will cause you to have to re-run the dialyzer build for your project

### Logs
This keeps repeating forever 
```
[Info  - 13:39:01] [ElixirLS WorkspaceSymbols] 0 modules need reindexing
[Info  - 13:39:01] [ElixirLS WorkspaceSymbols] 0 modules added to index
[Info  - 13:39:01] [ElixirLS WorkspaceSymbols] 0 functions added to index
[Info  - 13:39:01] [ElixirLS WorkspaceSymbols] 0 types added to index
[Info  - 13:39:01] [ElixirLS WorkspaceSymbols] 0 callbacks added to index
# Compile logs
MIX_ENV: test
MIX_TARGET: 
Compiling 191 files (.ex)
```

**Comment by axelson** [comment] 2021-08-09 23:18
@Awlexus does this persist after removing the `.elixir_ls` directory? (see https://github.com/elixir-lsp/elixir-ls#troubleshooting for details). If so please share a sample project that has the issue.

**Comment by Awlexus** [comment] 2021-08-21 15:46
@axelson Sorry for replying so late. Yes, this unfortunately persists even following these steps. For the same project, I tried to create it on a different computer, so I can confirm this happening on 3 different PCs. 

I don't think it's worth creating a share a sample, because these are the only steps required to make one:
* Create a new project with `mix new`
* Add `{:yaws, github: "erlyaws/yaws"}` to the dependencies

**Comment by lauritzsh** [comment] 2021-12-27 15:28
This seems to happen (or something similar at least) with https://github.com/gleam-lang/mix_gleam too, did you happen to find a fix for this?

**Comment by lukaszsamson** [comment] 2021-12-28 08:57
@lauritzsh cannot reproduce
```
Started ElixirLS v0.8.2
Elixir version: "1.13.1 (compiled with Erlang/OTP 24)"
Erlang version: "24"
ElixirLS compiled with Elixir 1.10.4 and erlang 22
MIX_ENV: dev
MIX_TARGET: 
==> nimble_parsec
Compiling 4 files (.ex)
Generated nimble_parsec app
==> makeup
Compiling 44 files (.ex)
[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/algol_nu.ex:34: Makeup.Styles.HTML.Algol_NuStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/arduino.ex:34: Makeup.Styles.HTML.ArduinoStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/algol.ex:34: Makeup.Styles.HTML.AlgolStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/borland.ex:40: Makeup.Styles.HTML.BorlandStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/abap.ex:27: Makeup.Styles.HTML.AbapStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/autumn.ex:50: Makeup.Styles.HTML.AutumnStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/bw.ex:39: Makeup.Styles.HTML.BlackWhiteStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/colorful.ex:66: Makeup.Styles.HTML.ColorfulStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/default.ex:57: Makeup.Styles.HTML.DefaultStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/emacs.ex:58: Makeup.Styles.HTML.EmacsStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/friendly.ex:58: Makeup.Styles.HTML.FriendlyStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/fruity.ex:34: Makeup.Styles.HTML.FruityStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/igor.ex:26: Makeup.Styles.HTML.IgorStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/lovelace.ex:67: Makeup.Styles.HTML.LovelaceStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/manni.ex:58: Makeup.Styles.HTML.ManniStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/monokai.ex:44: Makeup.Styles.HTML.MonokaiStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/murphy.ex:66: Makeup.Styles.HTML.MurphyStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/native.ex:49: Makeup.Styles.HTML.NativeStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/paraiso-dark.ex:52: Makeup.Styles.HTML.ParaisoDarkStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/paraiso-light.ex:52: Makeup.Styles.HTML.ParaisoLightStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/pastie.ex:59: Makeup.Styles.HTML.PastieStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/perldoc.ex:51: Makeup.Styles.HTML.PerldocStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/rainbow_dash.ex:54: Makeup.Styles.HTML.RainbowDashStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/rrt.ex:27: Makeup.Styles.HTML.RrtStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/samba.ex:85: Makeup.Styles.HTML.SambaStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/tango.ex:85: Makeup.Styles.HTML.TangoStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/trac.ex:49: Makeup.Styles.HTML.TracStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/vim.ex:44: Makeup.Styles.HTML.VimStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/vs.ex:32: Makeup.Styles.HTML.VisualStudioStyle.style/0

[Warn  - 9:38:11 AM] warning: the @style_struct() notation (with parenthesis) is deprecated, please use @style_struct (without parenthesis) instead
  lib/makeup/styles/html/pygments/xcode.ex:38: Makeup.Styles.HTML.XcodeStyle.style/0

Generated makeup app
==> earmark
Compiling 1 file (.yrl)
Compiling 2 files (.xrl)
Compiling 3 files (.erl)
Compiling 32 files (.ex)
Generated earmark app
==> makeup_elixir
Compiling 4 files (.ex)
Compiling lib/makeup/lexers/elixir_lexer.ex (it's taking more than 10s)
Generated makeup_elixir app
==> ex_doc
Compiling 22 files (.ex)
Generated ex_doc app
==> mix_gleam
Compiling 9 files (.ex)
[Warn  - 9:38:29 AM] warning: ElixirLS.LanguageServer.MixShell.cmd/1 defined in application :language_server is used by the current application but the current application does not depend on :language_server. To fix this, you must do one of:

  1. If :language_server is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :language_server is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :language_server, you may optionally skip this warning by adding [xref: [exclude: [ElixirLS.LanguageServer.MixShell]]] to your "def project" in mix.exs

  lib/mix/tasks/gleam/compile.ex:151: Mix.Tasks.Gleam.Compile.compile_package/2

[Warn  - 9:38:29 AM] warning: ElixirLS.LanguageServer.MixShell.error/1 defined in application :language_server is used by the current application but the current application does not depend on :language_server. To fix this, you must do one of:

  1. If :language_server is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :language_server is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :language_server, you may optionally skip this warning by adding [xref: [exclude: [ElixirLS.LanguageServer.MixShell]]] to your "def project" in mix.exs

Invalid call found at 2 locations:
  lib/mix_gleam/io.ex:21: MixGleam.IO.shell_warn/3
  lib/mix_gleam/io.ex:22: MixGleam.IO.shell_warn/3

[Warn  - 9:38:29 AM] warning: ElixirLS.LanguageServer.MixShell.info/1 defined in application :language_server is used by the current application but the current application does not depend on :language_server. To fix this, you must do one of:

  1. If :language_server is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :language_server is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :language_server, you may optionally skip this warning by adding [xref: [exclude: [ElixirLS.LanguageServer.MixShell]]] to your "def project" in mix.exs

Invalid call found at 10 locations:
  lib/mix/tasks/gleam/compile.ex:148: Mix.Tasks.Gleam.Compile.compile_package/2
  lib/mix/tasks/gleam/deps/get.ex:47: Mix.Tasks.Gleam.Deps.Get.run/1
  lib/mix/tasks/gleam/deps/get.ex:72: Mix.Tasks.Gleam.Deps.Get.run/1
  lib/mix/tasks/gleam/new.ex:41: Mix.Tasks.Gleam.New.run/1
  lib/mix/tasks/gleam/new.ex:52: Mix.Tasks.Gleam.New.retro/0
  lib/mix/tasks/gleam/new.ex:53: Mix.Tasks.Gleam.New.retro/0
  lib/mix/tasks/gleam/test.ex:45: Mix.Tasks.Gleam.Test.run/1
  lib/mix_gleam/io.ex:16: MixGleam.IO.shell_info/3
  lib/mix_gleam/io.ex:17: MixGleam.IO.shell_info/3
  lib/mix_gleam/io.ex:26: MixGleam.IO.gleam_env_info/0

Generated mix_gleam app
[Info  - 9:38:30 AM] Compile took 21889 milliseconds
[Info  - 9:38:30 AM] [ElixirLS WorkspaceSymbols] Indexing...
MIX_ENV: dev
MIX_TARGET: 
[Info  - 9:38:30 AM] Compile took 303 milliseconds
[Info  - 9:38:30 AM] [ElixirLS Dialyzer] Checking for stale beam files
[Info  - 9:38:30 AM] [ElixirLS WorkspaceSymbols] Module discovery complete
[Info  - 9:38:30 AM] [ElixirLS WorkspaceSymbols] 84 callbacks added to index
[Info  - 9:38:31 AM] [ElixirLS WorkspaceSymbols] 585 modules added to index
[Info  - 9:38:32 AM] [ElixirLS WorkspaceSymbols] 520 types added to index
[Info  - 9:38:34 AM] [ElixirLS Dialyzer] Found 161 changed files in 4204 milliseconds
[Info  - 9:38:38 AM] [ElixirLS WorkspaceSymbols] 8455 functions added to index
[Info  - 9:38:43 AM] [ElixirLS Dialyzer] Analyzing 161 modules: [Makeup.Registry, Earmark.Line.Heading, ExDoc.Utils.SimpleJSON, :link_text_parser, Earmark.Block.Para, Makeup.Styles.HTML.PastieStyle, Earmark.Helpers, Earmark.Block.IdDef, ExDoc.Application, Makeup.Styles.HTML.AbapStyle, ExDoc.GroupMatcher, Earmark.Options, ExDoc.ModuleNode, Makeup.Application, ExDoc.Autolink, Earmark.Line.Indent, Earmark.Ast.Inline, Makeup.Token.Utils, Makeup.Styles.HTML.BorlandStyle, ExDoc.TypeNode, Earmark.CLI, Makeup.Styles.HTML.EmacsStyle, ExDoc, Earmark.Block.FnList, Earmark.Error, Earmark.Ast.Renderer.TableRenderer, Earmark.Block.ListItem, Makeup.Styles.HTML.VisualStudioStyle, Earmark.Block.Ruler, Earmark.Block.Ial, ExDoc.Retriever.Error, Mix.Tasks.Gleam.New, Makeup.Styles.HTML.AlgolStyle, Makeup.Styles.HTML, Earmark.Line.HtmlCloseTag, Mix.Tasks.Gleam.Test, Earmark.Helpers.YeccHelpers, Makeup.Styles.HTML.RainbowDashStyle, Earmark.Line.FnDef, Makeup.Token.Utils.Hierarchy, Mix.Tasks.Docs, Earmark.Helpers.AstHelpers, Earmark.Ast.Renderer.FootnoteListRenderer, Makeup.Styles.HTML.TangoStyle, Earmark.Helpers.LinkParser, Makeup.Formatters.HTML.HTMLFormatter, MixGleam, Mix.Tasks.NimbleParsec.Compile, MixGleam.Error, Earmark.Helpers.HtmlHelpers, ...]
[Info  - 9:41:17 AM] [ElixirLS Dialyzer] Analysis finished in 163180 milliseconds
[Info  - 9:41:17 AM] Dialyzer analysis is up to date
[Info  - 9:41:18 AM] [ElixirLS Dialyzer] Writing manifest...
[Info  - 9:41:18 AM] [ElixirLS Dialyzer] Done writing manifest in 1112 milliseconds.
```

@Awlexus The behaviour is expected. Elixir-LS uses file watchers to monitor sources and deps for changes. If this library modifies its sources during compilation, then a file watcher is triggered. Elixir mix is going to introduce file watchers in the near future so this is going to be a common behaviour.

My suggestion is to fix this library to behave in a sane way or create a pull request which will allow for excluding certain paths from file watcher rules.

**Closed by lukaszsamson** 2021-12-28 08:57 UTC
