### ISSUE TITLE
The server stops working as soon as "&" you type. OTP26

### ISSUE THREAD

**Issue by uhlikosaurus** [elixir-lsp/elixir-ls#1039] opened 2023-12-12 07:26 UTC
Windows 11
OTP26
VSCode with extension **ElixirLS: Elixir support and debugger v0.17.10**

When writing an anonymous function with the wildcard "&" the server stops working.

How to reproduce the problem:

```
def foo() do
    "foo"
    |> (&
  end
```

> [Error - 8:14:09 AM] Stopping server failed
> Error: Stopping the server timed out
> 	at c:\Users\uhlik\.vscode\extensions\jakebecker.elixir-ls-0.17.10\out\extension.js:89:9067

**Comment by lukaszsamson** [comment] 2023-12-12 07:57
Duplicate of https://github.com/elixir-lsp/elixir-ls/issues/1023. Please downgrade to OTP 25 or wait for the fix in OTP 26.2

**Closed by lukaszsamson** 2023-12-12 07:57 UTC

**Comment by lukaszsamson** [comment] 2023-12-22 07:03
OTP 26.2.1 is out and with with fix for this issue
