### ISSUE TITLE
do<enter><tab> expands as snippet, replacing `do` with `defoverridable()`

### ISSUE THREAD

**Issue by mikl** [elixir-lsp/elixir-ls#630] opened 2021-11-24 01:16 UTC
### Environment

* Elixir & Erlang versions (elixir --version): 

```
Erlang/OTP 24 [erts-12.1.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Elixir 1.12.3 (compiled with Erlang/OTP 24)
```

* Operating system: MacOS 12.1
* Editor or IDE name (e.g. Emacs/VSCode): VSCode 1.62.3
* Editor Plugin/LSP Client name: ElixirLS

### Troubleshooting

- [x] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [x] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor

### Logs

(Not an error, no relevant logs)

---

## Issue

This is very similar to #610, but a slightly different pattern.

This happens when you don’t use a snippet while defining a block, like if you just type `def x do<enter><tab>`. The reason I press tab here is because VSCode does not add an indent level by itself, so to have properly indented code inside the do-block, pressing tab is the natural thing to do. Unfortunately, tab is also the default binding for expanding snippets in VSCode, so it decides that I was trying to type `defoverridable()`, so deletes my linebreak and replaces the `do` with that.
To get around this, I have to consciously avoid properly indenting the new block and instead rely on the code formatter to do it for me.

I have tried finding a way to tell VSCode that `defoverridable()` is not a snippet I want to expand _ever_, but I have not been able to find a way.

**Comment by mikl** [comment] 2021-11-24 01:20
Also related: #593 – unfortunately, this issue still haunts me in ElixirLS v0.8.1.

**Comment by mikl** [comment] 2021-11-24 01:23
Defining a do-block snippet as mentioned in [this comment](https://github.com/elixir-lsp/elixir-ls/pull/593#issuecomment-915350274) does make the problem go away, so that might be a possible workaround.

**Comment by ChilloManiac** [comment] 2022-02-15 07:26
Also present for me in 0.9.0

**Comment by lukaszsamson** [comment] 2022-10-02 12:58
Fixed in https://github.com/elixir-lsp/elixir-ls/commit/e4576def20c479dc7be7cc7e6079d017cb980c98 and released in v0.11

**Closed by lukaszsamson** 2022-10-02 12:58 UTC

**Comment by RobertYost** [comment] 2022-10-18 14:49
still running into this issue on v0.11 😅 I am using neovim with nvim-lsp. Deleted my project's .elixir_ls folder and no change unfortunately. Tested with vscode as well, and it seems to work as intended there, not sure why the functionality would be different though. Going to mess around some more with my lsp config and see if it's an issue there maybe

**Comment by lukaszsamson** [comment] 2022-10-18 14:52
@RobertYost my guess is nvim-lsp is sorting items differently or not respecting the `preselect` flag...
