### ISSUE TITLE
VM hangs after update to 0.14.0

### ISSUE THREAD

**Issue by kkalb** [elixir-lsp/elixir-ls#865] opened 2023-04-14 08:39 UTC
Feel free to delete this issue or the one on the vscode/elixir_ls side
https://github.com/elixir-lsp/vscode-elixir-ls/issues/318

Hello!

After I reloaded vscode after it updated the extension, my virtual machine completely freezes.
I retried 6 times now and it's the same everytime. I can not look anything up in vscode because after starting it, it hangs.

In .vscode/extensions I find jakebecker.elixir-ls-0.14.0 which was updated/released this night (04/14/23)

Task manager on host shows 30% CPU and 50% disk usage for the VM alone (system is on higher end regarding specs).

When I run a script to recompile/release elixir_ls in the extension folder with my elixir/erlang versions, it crashes on vscode boot but I now can use vscode again.

Elixir & Erlang versions (elixir --version):

- Elixir: 1.14.1-otp-25
- Erlang: 25.2.1

VSCode ElixirLS version:

- Todays update (0.14.0)

Operating System Version:

- Ubuntu 22.04 (VirtualBox) on Windows host

**Comment by rmand97** [comment] 2023-04-14 08:56
Me too. I downgraded to version 0.13.0 for it to work.

**Comment by kkalb** [comment] 2023-04-14 09:01
> Me too. I downgraded to version 0.13.0 for it to work.

Did you downgrade manually or can you tell vscode to use an older version somehow?

**Comment by rmand97** [comment] 2023-04-14 09:35
You can select the version you want on the extension. 

![downgrade_elixirls](https://user-images.githubusercontent.com/102654833/232007492-4f58dda3-921a-4878-a4fa-fe0554146243.png)

**Comment by kkalb** [comment] 2023-04-14 09:39
Not really because we are not able to reach this; because it hangs..

I am trying to install it with a command but can not manage to find the correct one

**Comment by kkalb** [comment] 2023-04-14 09:47
I managed to find the correct command:

First of all go to your home folder

```bash
~/.vscode/extensions
```

and make sure to delete

```bash
jakebecker.elixir-ls-0.14.0
```
then open vscode, open a terminal and type
```bash
code --install-extension jakebecker.elixir-ls@0.13.0
```
Afterwards go to your extensions and "Enable" the extension, but do not update it until a hotfix is also applied to the vscode-elixir-ls repo. Elixir-ls main repo released 0.14.1 the time writing.

**Comment by JVZELLER** [comment] 2023-04-14 16:52
For people using VSCodium, the commands are almost the same:

```bash
rm -rf  ~/.vscode-oss/extensions/elixir-lsp.elixir-ls-0.14.0-universal
```
```bash
codium --install-extension lixir-lsp.elixir-ls@0.13.0
```

Alternatively, you can open a non-elixir project and reinstall the extension in the extensions menu.

**Comment by henriqueberlesi** [comment] 2023-04-14 18:37
Having the same issue using Ubuntu 22.04.2 LTS (natively).

Downgrading to version 0.13.0 seems to fix the issue.

--

> Not really because we are not able to reach this; because it hangs..

Opening a non-Elixir project seems to work as well. I've opened VSCode using the terminal with `code <non-elixir-project>` and was able to downgrade using the GUI.

**Comment by guigaoliveira** [comment] 2023-04-14 18:44
Same here.

**Comment by kasvith** [comment] 2023-04-15 10:33
Same issue

**Comment by jameskentTX** [comment] 2023-04-15 14:10
Same here. Computer freeze completely when I open `exs` file with `ElixirLS` enabled. I have to reboot my PC.

**Comment by tfl** [comment] 2023-04-15 14:16
Same here. At the moment the extension is loaded HDD-IO goes though the roof. CPU load is also very heavy. Both caused by the Erlang VM process. The computer is not useable anymore and I have to press Reset.

**Comment by jameskentTX** [comment] 2023-04-15 14:25
The is a new version: `jakebecker.elixir-ls-0.14.2`
It is working fine.

**Comment by ramyma** [comment] 2023-04-15 15:19
I'm still getting this error with `jakebecker.elixir-ls-0.14.2`:
```
** (Mix.Error) No package with name stream_data (from: deps/elixir_ls/apps/language_server/mix.exs) in registry
    (mix 1.14.4) lib/mix.ex:513: Mix.raise/2
    (hex 2.0.6) lib/hex/remote_converger.ex:317: Hex.RemoteConverger.verify_package_req/4
    (elixir 1.14.4) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
    (hex 2.0.6) lib/hex/remote_converger.ex:306: Hex.RemoteConverger.verify_input/2
    (hex 2.0.6) lib/hex/remote_converger.ex:52: Hex.RemoteConverger.converge/2
    (mix 1.14.4) lib/mix/dep/converger.ex:118: Mix.Dep.Converger.all/4
    (mix 1.14.4) lib/mix/dep/converger.ex:74: Mix.Dep.Converger.converge/4
    (mix 1.14.4) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
[Error - 5:16:27 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 5:16:27 PM] The ElixirLS - ex_sd server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 5:16:27 PM] ElixirLS - ex_sd client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 5:16:27 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

When I rollback to version `0.13.0` everything works fine.

**Comment by jameskentTX** [comment] 2023-04-15 15:56
I've restarted PC, deleted old version of `ElixirLS` in directory:  `~/.vscode/extensions`, and some cached files and folders in  `~/.config/Code` too.
Then I opened `vscode` and installed new version of `ElixirLS`.

**Comment by alaadahmed** [comment] 2023-04-15 18:42
Still getting crashing errors even after upgrading to `0.14.2`
```
Starting ElixirLS release v0.14.2
Running in /Users/alaadahmed/Codes/myapp
[Error - 2:39:43 PM] Client ElixirLS - myapp: connection to server is erroring. Shutting down server.
[Error - 2:39:43 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
    at LanguageClient.shutdown (/Users/alaadahmed/.vscode/extensions/jakebecker.elixir-ls-0.14.2/node_modules/vscode-languageclient/lib/common/client.js:914:19)
    at LanguageClient.stop (/Users/alaadahmed/.vscode/extensions/jakebecker.elixir-ls-0.14.2/node_modules/vscode-languageclient/lib/common/client.js:885:21)
    at LanguageClient.stop (/Users/alaadahmed/.vscode/extensions/jakebecker.elixir-ls-0.14.2/node_modules/vscode-languageclient/lib/node/main.js:150:22)
    at LanguageClient.handleConnectionError (/Users/alaadahmed/.vscode/extensions/jakebecker.elixir-ls-0.14.2/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[Error - 2:39:43 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 2:39:43 PM] The ElixirLS - myapp server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 2:39:43 PM] ElixirLS - myapp client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 2:39:43 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by lukaszsamson** [comment] 2023-04-15 19:01
@ramyma are you running a custom package registry without stream_data?

@alaadahmed please post some details on your setup

**Comment by ramyma** [comment] 2023-04-15 19:28
> @ramyma are you running a custom package registry without stream_data?
> 
@lukaszsamson I'm using the standard setup.

**Comment by alaadahmed** [comment] 2023-04-15 20:31
@lukaszsamson my setup is:
macOS `13.3.1`
vscode `1.77.3`
elixir: `1.14.4`
erlang: `25.3`
elixir-ls: `0.14.2`

After updating elixir-ls to `0.14.2`, and it crashes multiple times, and just doesn't work. Before that I updated to `0.14.0` and had the same issue of multiple crashes, but I didn't have any hanging VM or so, just crashes. So now I downgraded to `0.13.0` again, and it works as it was actually.

**Comment by dvic** [comment] 2023-04-15 20:33
For me 0.14.2 fixes the issue, thanks 👍

**Comment by lukaszsamson** [comment] 2023-04-15 22:21
@alaadahmed How did you install elixir? Do you use asdf-vm? Can you try running `~/.vscode/extensions/jakebecker.elixir-ls-0.14.2/elixir-ls-release/language_server.sh` in terminal?

**Comment by alaadahmed** [comment] 2023-04-15 22:52
I installed elixir/erlang using `asdf`, and when running that script I got this output:
```
Starting ElixirLS release v0.14.2
Running in /Users/alaadahmed
Content-Length: 103

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Started ElixirLS v0.14.2","type":3}}Content-Length: 107

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Running in /Users/alaadahmed","type":3}}Content-Length: 130

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"ElixirLS built with elixir \"1.14.4\" on OTP \"25\"","type":3}}Content-Length: 151

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Running on elixir \"1.14.4 (compiled with Erlang/OTP 25)\" on OTP \"25\"","type":3}}Content-Length: 181

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Elixir sources not found (checking in /home/build/elixir). Code navigation to Elixir modules disabled.","type":3}}Content-Length: 111

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Experimental server is disabled.","type":3}}
Content-Length: 442

{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"** (RuntimeError) Unable to read from device: :invalid_content_length\n    (elixir_ls_utils 0.14.2) lib/packet_stream.ex:34: anonymous fn/1 in ElixirLS.Utils.PacketStream.stream/1\n    (elixir 1.14.4) lib/stream.ex:1619: Stream.do_resource/5\n    (elixir 1.14.4) lib/stream.ex:1813: Enumerable.Stream.do_each/4\n    (elixir 1.14.4) lib/stream.ex:689: Stream.run/1","type":2}}%
```

**Comment by alaadahmed** [comment] 2023-04-16 02:21
Sorry @lukaszsamson, my fault, I work on many projects, and the one that when I open, elixir-ls crashes is using elixir `1.13.2-otp-24`, but other one that uses latest elixir `1.14.4-otp-25` elixir-ls doesn't crash when opening it. So I think the issue in the version of elixir `1.13.2-otp-24` installed using `asdf`.

**Comment by Hentioe** [comment] 2023-04-16 03:56
Version `0.14.2` is working fine on my end. My environment is Elixir `v1.14.4`, Erlang `v25.3`, NixOS and asdf version management.

**Comment by tt67wq** [comment] 2023-04-16 09:07
My end looks like this:
```
$ ~/.vscode/extensions/jakebecker.elixir-ls-0.14.2/elixir-ls-release/language_server.sh
Starting ElixirLS release v0.14.2
Running in /home/tt67wq/Project/hope/kaiden
** (Mix.Error) Command "git --git-dir=.git fetch --force --quiet --progress --tags" failed
    (mix 1.14.4) lib/mix.ex:513: Mix.raise/2
    (mix 1.14.4) lib/mix/scm/git.ex:132: Mix.SCM.Git.checkout/2
    (elixir 1.14.4) lib/file.ex:1607: File.cd!/2
    (mix 1.14.4) lib/mix/dep/fetcher.ex:61: Mix.Dep.Fetcher.do_fetch/3
    (mix 1.14.4) lib/mix/dep/converger.ex:213: Mix.Dep.Converger.all/9
    (mix 1.14.4) lib/mix/dep/converger.ex:146: Mix.Dep.Converger.all/7
    (mix 1.14.4) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
    (mix 1.14.4) lib/mix/dep/converger.ex:74: Mix.Dep.Converger.converge/4
```
language versions:
erlang ref:OTP-25.3
elixir 1.14.4

**Comment by lucas-nelson** [comment] 2023-04-17 06:34
This might help, after noticing: https://github.com/elixir-lsp/elixir-ls/blob/7df86719f612a019ba1dccdf2c1d12864546d777/apps/elixir_ls_utils/lib/launch.ex#L19

## Elixir 1.14

```
$ iex
Erlang/OTP 25 [erts-13.1.5] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Interactive Elixir (1.14.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> System.put_env([{"MIX_ENV", nil}, {"MIX_TARGET",nil}])
:ok
```

## Elixir 1.13

```
$ iex
Erlang/OTP 24 [erts-12.3.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [dtrace]

Interactive Elixir (1.13.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> System.put_env([{"MIX_ENV", nil}, {"MIX_TARGET",nil}])
** (FunctionClauseError) no function clause matching in System.put_env/2    
    
    The following arguments were given to System.put_env/2:
    
        # 1
        "MIX_ENV"
    
        # 2
        nil
    
    Attempted function clauses (showing 1 out of 1):
    
        def put_env(varname, value) when is_binary(varname) and is_binary(value)
    
    (elixir 1.13.4) lib/system.ex:720: System.put_env/2
    (elixir 1.13.4) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
```

**Comment by lukaszsamson** [comment] 2023-04-18 15:38
@tt67wq are you able to debug why mix is not able to call git on your machine?

**Comment by tt67wq** [comment] 2023-04-18 16:00
> 

I restart vscode several times and it works now  ==, wired....

**Comment by tt67wq** [comment] 2023-04-18 16:01
> @tt67wq are you able to debug why mix is not able to call git on your machine?

I restart vscode several times and it works now ==, wired....

**Comment by lukaszsamson** [comment] 2023-04-21 11:25
I'm going to close this. If anyone still experiencing problems on 0.14.5 please open a new issue.

**Closed by lukaszsamson** 2023-04-21 11:25 UTC
