### ISSUE TITLE
@spec suggestions not working, possibly due to erlang :badrecord error

### ISSUE THREAD

**Issue by jfacoustic** [elixir-lsp/elixir-ls#702] opened 2022-06-17 00:10 UTC
### Environment

* Elixir & Erlang versions (elixir --version): 

```
Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Elixir 1.13.4 (compiled with Erlang/OTP 24)
```

* Elixir Language Server version: 0.9.0 
* Operating system: Mac (M1, Monterey 12.4)
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name and version: ElixirLS 0.9.0

### Current behavior

@spec suggestions are not showing up in editor even though I have them turned on in settings (both project and editor-wide).

This occurs for brand new projects as well as existing ones which previously worked.

The VSCode ElixirLS output says the following:

```
17:58:38.080 [error] Process #PID<0.181.0> raised an exception
** (ErlangError) Erlang error: {:badrecord, {:analysis, :undefined, :succ_typings, [], :undefined, ['/Users/joshuamathews/Documents/test_proj/.elixir_ls/build/_test/lib/test_proj/consolidated/Elixir.Collectable.beam', '/Users/joshuamathews/Documents/test_proj/.elixir_ls/build/_test/lib/test_proj/consolidated/Elixir.Enumerable.beam', '/Users/joshuamathews/Documents/test_proj/.elixir_ls/build/_test/lib/test_proj/consolidated/Elixir.IEx.Info.beam', '/Users/joshuamathews/Documents/test_proj/.elixir_ls/build/_test/lib/test_proj/consolidated/Elixir.Inspect.beam', '/Users/joshuamathews/Documents/test_proj/.elixir_ls/build/_test/lib/test_proj/consolidated/Elixir.List.Chars.beam', '/Users/joshuamathews/Documents/test_proj/.elixir_ls/build/_test/lib/test_proj/consolidated/Elixir.String.Chars.beam', '/Users/joshuamathews/Documents/test_proj/.elixir_ls/build/_test/lib/test_proj/ebin/Elixir.TestProj.beam'], [], :byte_code, {:plt, #Reference<0.3702252738.1662386178.102952>, #Reference<0.3702252738.1662386178.102954>, #Reference<0.3702252738.1662386178.102953>, #Reference<0.3702252738.1662386178.102955>, #Reference<0.3702252738.1662386178.102956>}, true, false, false, false, :none, [], []}}
    dialyzer_analysis_callgraph.erl:70: :dialyzer_analysis_callgraph.start/3
```

**Comment by jfacoustic** [comment] 2022-06-17 00:36
Tried this on an intel mac with 

```
Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.11.4 (compiled with Erlang/OTP 23)
```

And spec tags work as expected

**Comment by jfacoustic** [comment] 2022-06-17 00:42
After upgrading my elixir version on that intel mac, I get the same error.  (OTP 25, Elixir 1.13.4

**Comment by lukaszsamson** [comment] 2022-06-17 05:25
Duplicate of https://github.com/elixir-lsp/elixir-ls/issues/696. Downgrade to OTP 24 or compile ElixirLS on OTP 25

**Closed** 2022-06-19 12:51 UTC
