### ISSUE TITLE
Feature Request: Support mix format plugins

### ISSUE THREAD

**Issue by axelson** [elixir-lsp/elixir-ls#660] opened 2022-01-21 10:49 UTC
Elixir 1.13 added mix format plugins: https://hexdocs.pm/mix/1.13.2/Mix.Tasks.Format.html#module-plugins

ElixirLS should support these plugins if defined in the user's project.

Initially requested in: https://github.com/elixir-lsp/vscode-elixir-ls/discussions/224

**Comment by megalithic** [comment] 2022-01-21 14:57
Would this also enable support for elixir-ls to format, via LSP, *.html.heex files, too?

**Comment by zachdaniel** [comment] 2022-02-02 20:00
I may have time to make a PR to add support for this, what has to be done to make it work?

**Comment by msaraiva** [comment] 2022-02-04 21:50
@zachdaniel -> https://github.com/elixir-lsp/vscode-elixir-ls/discussions/224#discussioncomment-2092096

**Comment by megalithic** [comment] 2022-02-08 17:31
Super pumped for this!

**Comment by anildigital** [comment] 2022-02-23 08:29
Anyone know if it works for elixir-ls in Emacs?

**Comment by benvp** [comment] 2022-04-07 05:41
With the recent addition of the LiveView formatter in 0.17.8 I noticed that the formatting does work automatically in VSCode when using .ex files with the `~H` sigil. But using `html.heex` files it gives the following error:

```
[Error - 07:32:49] Request textDocument/formatting failed.
  Message: Unable to format due to syntax error
  Code: -32603 
MIX_ENV: test
MIX_TARGET: 
```

I used the sample code from the elixir formatter docs.

test.html.heex:

```html
<section><h1>   <b><%= @user.name %></b></h1></section>
```

.formatter.exs

```elixir
[
  import_deps: [:phoenix],
  plugins: [Phoenix.LiveView.HTMLFormatter],
  inputs: ["*.{heex,ex,exs}", "priv/*/seeds.exs", "{config,lib,test}/**/*.{heex,ex,exs}"]
]
```

**Comment by benvp** [comment] 2022-04-08 07:16
@frankdugan3 Yeah I did that. Also deleted the build and deps folder. When running `mix format` directly on the `.html.heex`file formatting works. But not when running through VSCode with the Elixir LSP.

**Comment by frankdugan3** [comment] 2022-04-08 14:03
@benvp I forgot to mention it, but it also requires [Elixir `v1.13.4`](https://github.com/phoenixframework/phoenix_live_view/blob/master/lib/phoenix_live_view/html_formatter.ex#L7). What version are you running?

**Comment by littleStudent** [comment] 2022-04-08 20:34
I have the exact same situation as @benvp described.
* running `mix format` in the console works
* running the formatter through vscode results in the described error
* I have version 1.13.4 running

**Comment by DaliborHorinek** [comment] 2022-04-19 18:58
I can confirm the same issue. 

elixir v1.13.4
neovim 0.7.0 + lspconfig and ElixirLS build from master (7f37d59ffe7952d70ddc2f44100227d558c8ef6e)

.formatter.exs
```
[
  plugins: [Phoenix.LiveView.HTMLFormatter],
  import_deps: [:ecto, :phoenix],
  inputs: ["*.{heex,ex,exs}", "priv/*/seeds.exs", "{config,lib,test}/**/*.{heex,ex,exs}"],
  subdirectories: ["priv/*/migrations"]
]
```

Phoenix LiveView 
```
      {:phoenix_live_view, "~> 0.17.9"},
```

.ex files with ~H are formatted correctly

 .heex file returns error 

```
"rpc.receive"   {  error = {    code = -32603,    message = "Unable to format due to syntax error"  },  id = 4,  jsonrpc = "2.0"}
```

Added inspect for the exception
```
Error: %SyntaxError{
  column: 1,
  description: "syntax error before: '<'",
  file: "nofile",
  line: 1,
  snippet: %{content: "<div><%= @inner_content %></div>", 
  offset: 0
}
```

**Comment by inoas** [comment] 2022-04-25 16:22
Slightly OT, VSCode instructions

For anything to work, you will need a recent Elixir version. I got 1.13.4 running. Also `.formatters.exs` must contain heex and the HTMLFormatter plugin:

```
[
  import_deps: [:ecto, :phoenix],
  plugins: [Phoenix.LiveView.HTMLFormatter],
  inputs: ["*.{heex,ex,exs}", "priv/*/seeds.exs", "{config,lib,test}/**/*.{heex,ex,exs}"],
  subdirectories: ["priv/*/migrations"]
]
```

Then apparently the `.heex`-files and `~H`-sigil formatting isn't the same.

At least for me this plugin does not work with `mix format` from VSCode, neither calling it from the command bar in VSCode nor on autoformat on save.

```
ElixirLS: Elixir support and debugger
Id: JakeBecker.elixir-ls
Description: Elixir support with debugger, autocomplete, and more. Powered by ElixirLS.
Version: 0.9.0
Publisher: ElixirLS
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=JakeBecker.elixir-ls
```

However this plugin works for doing the same thing:

```
Name: Elixir Mix Formatter
Id: animus-coop.vscode-elixir-mix-formatter
Description: Elixir Mix Formatter integrated into Visual Studio Code.
Version: 1.0.1
Publisher: Animus Coop.
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=animus-coop.vscode-elixir-mix-formatter
```

You will have to change (or remove, and it will ask) the default formatter in your VSCode `settings.json`, example:

```json
"[phoenix-heex]": {
  "editor.defaultFormatter": "animus-coop.vscode-elixir-mix-formatter", // Relevant line
  "editor.detectIndentation": false,
  "editor.formatOnPaste": true,
  "editor.formatOnSave": true,
  "editor.formatOnType": true,
  "editor.tabSize": 2,
  "editor.trimAutoWhitespace": true,
  "files.insertFinalNewline": false,
  "files.trimTrailingWhitespace": true
},
```

I hope this anyone.

**Comment by DaliborHorinek** [comment] 2022-04-25 21:58
The actual problem (IMHO) is that ElixirLS uses `Code.format_string!` which receives options from `Mix.Tasks.Format.formatter_opts_for_file`, but `format_string!` doesn't accept plugins as an option. So it doesn't know how to format `.heex` files. 

`mix format` works because it understands the plugins. 

What can be done here, is to use [Mix.Tasks.Formatter.formatter_for_file/2](https://hexdocs.pm/mix/1.13/Mix.Tasks.Format.html#formatter_for_file/2) to format the source file, same as the `mix format` does.

Would this be a way to go? If this is valid, I might be able to prepare a PR for this.

**Comment by LOG67** [comment] 2022-06-06 04:36
Any update on this issue? It looks like the PR #690 is accepted but not merged. Thank you guys for your work on this!

**Closed** 2022-06-21 19:43 UTC
Labels: enhancement

**Comment by zachdaniel** [comment] 2022-06-21 19:45
🥳 🎉 🙇🏻 ❤️

**Comment by ddengler** [comment] 2024-03-28 14:46
Note for others or future me to find. My formatter failed with plugin not found on vscode elixir-ls ONLY. Console worked properly. The issue was that elixir-ls was building as test env.

This failed as a result:
`{:tailwind_formatter, "~> 0.4.0", only: :dev, runtime: false}`

This obviously works:
`{:tailwind_formatter, "~> 0.4.0", only: [:dev, :test], runtime: false}`

**Comment by lukaszsamson** [comment] 2024-03-28 15:07
@ddengler You can switch ElixirLS mix env to `dev` via extension config if that works better in your case

**Comment by jdsampayo** [comment] 2024-07-16 12:20
the suggestion of @lukaszsamson worked for me, I had `:phoenix_live_reload, "~> 1.2", only: :dev},` in a project and the extension default environment is `test`, switching it to `dev` and restarting VSCode fixed the issue.
