### ISSUE TITLE
BUG - imports through use are not available as completion candidates

### ISSUE THREAD

**Issue by victorolinasc** [elixir-lsp/elixir-ls#664] opened 2022-01-26 18:46 UTC
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.13.2 OTP 24.2
* Elixir Language Server version: master commit #1e7a52ca242bf06942c405aab043a612fcd2a211
* Operating system:  Linux
* Editor or IDE name (e.g. Emacs/VSCode):  Emacs
* Editor Plugin/LSP Client name and version: lsp-mode

### Current behavior

I have a module that does something like this:

```elixir
defmodule MySchema do
      defmacro __using__(_opts) do
        quote do
          use Ecto.Schema
          import Ecto.Changeset          
        end
      end
end
```

Then another with:

```elixir
defmodule SomeSchema do
  use MySchema

  def any_function(changeset) do
    changeset
    |> validate_<<pointer here>>
  end
end
```

It does not show the functions from `Ecto.Changeset` that are imported. The server does not log any error. The build went smoothly and prints this at the end:

```sh
Compile took 1457 milliseconds
[ElixirLS Dialyzer] Checking for stale beam files
[ElixirLS WorkspaceSymbols] Updating index...
[ElixirLS WorkspaceSymbols] 1 modules need reindexing
[ElixirLS WorkspaceSymbols] 0 callbacks added to index
[ElixirLS WorkspaceSymbols] 1 modules added to index
[ElixirLS WorkspaceSymbols] 1 types added to index
[ElixirLS WorkspaceSymbols] 10 functions added to index
[ElixirLS Dialyzer] Found 1 changed files in 66 milliseconds
[ElixirLS Dialyzer] Analyzing 1 modules: [xxxxxxxxxxxxxxx (I've hidden the module name just in case here)]
[ElixirLS Dialyzer] Analysis finished in 417 milliseconds
Dialyzer analysis is up to date
[ElixirLS Dialyzer] Writing manifest...
[ElixirLS Dialyzer] Done writing manifest in 3032 milliseconds.
```

### Expected behavior

Some versions ago it was suggesting imported functions just as well. I'll completely rebuild everything from ground zero another time just to be double sure but I think this is a regression.

**Comment by victorolinasc** [comment] 2022-01-26 19:49
In my case there is also a wrapping if on `MySchema` module like this:

```elixir
if Code.ensure_loaded?(Ecto.Schema) do
  defmodule MySchema do
      defmacro __using__(_opts) do
        quote do
          use Ecto.Schema
          import Ecto.Changeset          
        end
      end
  end
end
```

Though I am sure the dep is present and compiled. Either way I forced recompilation (by deleting the dependency and updating the project), the server said it was replacing the definition of the module in question. Not sure if this would break anything. It didn't before.

Also, the commit of elixir-sense here is: d344003762e4049d7cf423a1f1ff184996bd4fbe

**Comment by lukaszsamson** [comment] 2022-01-27 08:22
Works fine on latest master (built and executed on the exact same version of elixir and OTP).
<img width="978" alt="Screenshot 2022-01-27 at 09 18 41" src="https://user-images.githubusercontent.com/1078186/151319355-85945b4c-abd8-4b2e-ba2e-f85eef370846.png">

@victorolinasc unless you can reproduce it as a test case in this repo or elixir_sense, I'm going to close it as a duplicate of https://github.com/elixir-lsp/elixir-ls/issues/193

**Closed by lukaszsamson** 2022-01-27 08:22 UTC
Labels: duplicate

**Comment by victorolinasc** [comment] 2022-01-30 16:47
I've set up a new project with the structured I mentioned. https://github.com/victorolinasc/use_dep_issue

Not re-opening this because maybe I am doing something wrong here but will leave a screenshot of completions here:

![image](https://user-images.githubusercontent.com/376386/151708830-296e975f-0c71-42af-ac18-b6e329ee0777.png)

Everything compiled just fine.
