### ISSUE TITLE
Auto-formatter not removing unneeded line-breaks as mix format does.

### ISSUE THREAD

**Issue by bmfay** [elixir-lsp/elixir-ls#802] opened 2023-01-18 15:56 UTC
### Environment

* Elixir & Erlang versions (elixir --version): 1.13.4 / 24.3.4.6
* Elixir Language Server version: 0.13.0
* Operating system: macOS 12.5.1
* Editor or IDE name: VsCode
* Editor Plugin/LSP Client name and version:

### Current behavior

It seems there is a small discrepancy now between `mix format` and the auto-format on-save in ElixirLS.  `mix format` will remove unnecessary line breaks whereas ElixirLS will leave them.  Is this known/intentional?

The following is left unchanged via auto-format.

```
    assert %{sub_state_id: ["error"]} =
             %Address{} |> Address.changeset(attrs) |> errors_on()
```

### Expected behavior

To match `mix format` it would do:

```
    assert %{sub_state_id: ["error"]} = %Address{} |> Address.changeset(attrs) |> errors_on()
```

**Comment by lukaszsamson** [comment] 2023-02-11 07:13
I cannot reproduce that. Are you sure you don't have any other extension that does the formatting? Does hitting `cmd+shift+P` and `Format document` have the same behavior? Can you create a simple project that reproduces this?

**Comment by lukaszsamson** [comment] 2023-02-11 07:15
It may be related to https://github.com/elixir-lsp/elixir-ls/issues/526

**Comment by lukaszsamson** [comment] 2023-03-18 17:43
Closing due to lack of repro steps

**Closed by lukaszsamson** 2023-03-18 17:43 UTC
Labels: waiting for information
