### ISSUE TITLE
Server initialization failed.

### ISSUE THREAD

**Issue by conradwt** [elixir-lsp/elixir-ls#904] opened 2023-06-04 07:25 UTC
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.14.5 (compiled with Erlang/OTP 26)
* Elixir Language Server version: 0.14.7
* Operating system: macOS 13.4
* Editor or IDE name (e.g. Emacs/VSCode): 1.79.0-insider (Universal)
* Editor Plugin/LSP Client name and version: ElixirLS: Elixir support and debugger
v0.14.7
* Hardware: Apple M1 MacBook Pro

### Current behavior

Server initialization failed.

```zsh
Starting ElixirLS release v0.14.6
Running in /Users/conradwt/projects.dir/zero-to-graphql-using-elixir
[Info  - 12:06:22 AM] Started ElixirLS v0.14.6
[Info  - 12:06:22 AM] Running in /Users/conradwt/projects.dir/zero-to-graphql-using-elixir
[Info  - 12:06:22 AM] ElixirLS built with elixir "1.14.5" on OTP "26"
[Info  - 12:06:22 AM] Running on elixir "1.14.5 (compiled with Erlang/OTP 26)" on OTP "26"
[Info  - 12:06:22 AM] Protocols are not consolidated
[Info  - 12:06:22 AM] Elixir sources not found (checking in /home/build/elixir). Code navigation to Elixir modules disabled.
Runtime terminating during boot ({badarg,[{io,put_chars,[standard_error,[_]],[{_},{_},{_}]},{Elixir.Kernel.CLI,exec_fun,2,[{_},{_}]},{Elixir.Kernel.CLI,run,1,[{_},{_}]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
[Error - 12:06:24 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 12:06:24 AM] Connection to server got closed. Server will restart.
true
[Error - 12:06:24 AM] ElixirLS - zero-to-graphql-using-elixir client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

1. open a Phoenix project

### Expected behavior

I expected that the Elixir LS would work without fail.

**Comment by lukaszsamson** [comment] 2023-06-04 10:26
Please use search before opening new issues. Duplicate of https://github.com/elixir-lsp/elixir-ls/issues/886

**Closed by lukaszsamson** 2023-06-04 10:26 UTC

**Comment by conradwt** [comment] 2023-06-04 21:38
@lukaszsamson The issue that you referenced here doesn't specify the machine architecture or provide any type of logs to actually search against.  Thus, it's really impossible for me to make assumptions about #886 when trying to determine if my bug is a duplicate or not.  If you're wanting people to complete the bug template, then the maintainer of this repository should provide the same information in their bug reporting if you're expecting others to check for duplicates.  Finally, I highly recommend adding relevant information to your `README.md` regarding Erlang 26 and ELixirLS to let developers know the support status for ElixirLS using Erlang 26.  A compatibility matrix would better help developers in determining the exact OTP versions that are supported by ElixirLS.

**Comment by lukaszsamson** [comment] 2023-06-05 06:48
@conradwt Good ideas, please send PR
