### ISSUE TITLE
Disable "No mixfile found in project..." notification when working on exs files

### ISSUE THREAD

**Issue by Lindenk** [elixir-lsp/elixir-ls#435] opened 2020-12-07 19:45 UTC
When working on a one off script, the extension publishes a `No mixfile found in project. To use a subdirectory, set 'elixirLS.projectDir' in your settings` notification each time the file is saved. 

Expected Behavior: Do not spam "No mixfile found" messages when working on a script not using mix. A config option to disable the message entirely could also be an option.

### Environment

* Elixir & Erlang versions (elixir --version):
Erlang/OTP 23 [erts-11.1.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.11.0 (compiled with Erlang/OTP 23)

* Operating system: Arch Linux
* Editor or IDE name (e.g. Emacs/VSCode): VSCode

### Troubleshooting

- [X] Restart your editor (which will restart ElixirLS) sometimes fixes issues
- [X] Stop your editor, remove the entire `.elixir_ls` directory, then restart your editor

**Comment by lukaszsamson** [comment] 2020-12-07 20:45
Duplicate of https://github.com/elixir-lsp/elixir-ls/issues/307

**Closed by lukaszsamson** 2020-12-07 20:45 UTC
Labels: duplicate
