### ISSUE TITLE
Phoenix verified routes with params causing compilation error

### ISSUE THREAD

**Issue by clarkware** [elixir-lsp/elixir-ls#779] opened 2022-12-01 20:31 UTC
### Environment

* Elixir & Erlang versions (elixir --version):  1.14.2
* Elixir Language Server version: 0.12.0
* Operating system: Mac OS
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name and version: ElixirLS

### Current behavior

Given a Phoenix verified route with params that's in a Phoenix LiveView module (not in HEEx template), like so:

```
params = [page: 1, direction: "asc"]
~p"/posts?#{params}"
```

The Elixir LS log output has the following compilation error:

```
== Compilation error in file lib/my_app_web/live/my_live.ex ==
** (ArgumentError) expected query string param to be compile-time map or keyword list, got: "/posts?#{params}"
```

### Expected behavior

The same code doesn't produce a compilation error when running the standard "mix compile" task. 

And using the same verified route in a HEEx template like so does not produce the compilation error:

```
~p"/posts?#{[page: 1, direction: "asc"]}"
```

I'm not sure how Elixir LS is running the compiler differently than "mix compile" to get the compilation error.

Here's the full Elixir LS log output:

```
[Info  - 1:28:51 PM] Started ElixirLS v0.12.0
[Info  - 1:28:51 PM] ElixirLS built with elixir "1.14.2" on OTP "25"
[Info  - 1:28:51 PM] Running on elixir "1.14.2 (compiled with Erlang/OTP 25)" on OTP "25"
[Info  - 1:28:51 PM] Elixir sources not found (checking in /private/tmp/elixir-20221111-39429-u2qosx/elixir-1.14.2). Code navigation to Elixir modules disabled.
[Info  - 1:28:51 PM] Loaded DETS databases in 38ms
[Info  - 1:28:51 PM] Starting build with MIX_ENV: test MIX_TARGET: host
Compiling 66 files (.ex)

== Compilation error in file lib/my_app_web/live/my_live.ex ==
** (ArgumentError) expected query string param to be compile-time map or keyword list, got: "/posts?#{params}"
    (phoenix 1.7.0-rc.0) lib/phoenix/verified_routes.ex:625: Phoenix.VerifiedRoutes.raise_invalid_query/1
    (phoenix 1.7.0-rc.0) lib/phoenix/verified_routes.ex:548: Phoenix.VerifiedRoutes.verify_segment/3
    (phoenix 1.7.0-rc.0) lib/phoenix/verified_routes.ex:714: Phoenix.VerifiedRoutes.rewrite_path/4
    (phoenix 1.7.0-rc.0) lib/phoenix/verified_routes.ex:700: Phoenix.VerifiedRoutes.build_route/5
    (phoenix 1.7.0-rc.0) expanding macro: Phoenix.VerifiedRoutes.sigil_p/2
    lib/my_app_web/live/my_live.ex:40: MyAppWeb.MyLive.handle_event/3
```

**Comment by lukaszsamson** [comment] 2022-12-01 22:29
Duplicate of https://github.com/elixir-lsp/elixir-ls/issues/766

**Closed by lukaszsamson** 2022-12-01 22:29 UTC

**Comment by clarkware** [comment] 2022-12-01 22:52
Sorry, I looked around but somehow missed seeing the duplicate before posting this. 

Thank you!
