### ISSUE TITLE
ElixirLS doesn't show specs and docs with Phoenix 1.7.0-rc.0

### ISSUE THREAD

**Issue by kevinschweikert** [elixir-lsp/elixir-ls#801] opened 2023-01-16 17:03 UTC
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.14.3 (compiled with Erlang/OTP 25)
* Elixir Language Server version: v0.13.0
* Operating system: macOS Ventura
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* Editor Plugin/LSP Client name and version: 

Name: ElixirLS: Elixir support and debugger
Id: JakeBecker.elixir-ls
Description: Elixir support with debugger, autocomplete, and more. Powered by ElixirLS.
Version: 0.13.0
Publisher: ElixirLS
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=JakeBecker.elixir-ls

### Current behavior

We updated our project to phoenix 1.7.0-rc.0, and we don't get specs suggested, and the hover documentation doesn't work any more for project functions. External dependencies still work.
When we downgrade to a branch with phoenix 1.6.5 it works as expected.

We tried to build elixir-ls from source with OTP 25, but it doesn't change anything

#### Output

(Anonymized filenames because it's not relevant)

```
[Info  - 17:34:00] Started ElixirLS v0.13.0
[Info  - 17:34:00] ElixirLS built with elixir "1.14.3" on OTP "25"
[Info  - 17:34:00] Running on elixir "1.14.3 (compiled with Erlang/OTP 25)" on OTP "25"
[Info  - 17:34:00] Elixir sources not found (checking in /home/build/elixir). Code navigation to Elixir modules disabled.
[Info  - 17:34:00] Loaded DETS databases in 228ms
[Info  - 17:34:00] Starting build with MIX_ENV: dev MIX_TARGET: host
Compiling 54 files (.ex)

== Compilation error in file lib/app_web/live/views/app_live.ex ==
** (ArgumentError) expected query string param to be compile-time map or keyword list, got: "/some_route?#{params}"
    (phoenix 1.7.0-rc.0) lib/phoenix/verified_routes.ex:625: Phoenix.VerifiedRoutes.raise_invalid_query/1
    (phoenix 1.7.0-rc.0) lib/phoenix/verified_routes.ex:548: Phoenix.VerifiedRoutes.verify_segment/3
    (phoenix 1.7.0-rc.0) lib/phoenix/verified_routes.ex:714: Phoenix.VerifiedRoutes.rewrite_path/4
    (phoenix 1.7.0-rc.0) lib/phoenix/verified_routes.ex:700: Phoenix.VerifiedRoutes.build_route/5
    (phoenix 1.7.0-rc.0) expanding macro: Phoenix.VerifiedRoutes.sigil_p/2
    lib/app_web/live/views/app_live.ex:247: App.AppLive.handle_info/2
[Info  - 17:34:02] Compile took 1597 milliseconds
[Info  - 17:34:02] [ElixirLS WorkspaceSymbols] Indexing...
[Error - 17:34:02] Process #PID<0.662.0> raised an exception
** (ErlangError) Erlang error: :noproc:

  * 1st argument: the pid does not refer to an existing process

    :erlang.link(#PID<0.142.0>)
    (elixir 1.14.3) lib/module/parallel_checker.ex:56: anonymous fn/5 in Module.ParallelChecker.spawn/3
[Error - 17:34:02] Process #PID<0.663.0> raised an exception
** (ErlangError) Erlang error: :noproc:

  * 1st argument: the pid does not refer to an existing process

    :erlang.link(#PID<0.142.0>)
    (elixir 1.14.3) lib/module/parallel_checker.ex:56: anonymous fn/5 in Module.ParallelChecker.spawn/3
[Info  - 17:34:02] [ElixirLS WorkspaceSymbols] Module discovery complete
[Info  - 17:34:02] [ElixirLS WorkspaceSymbols] 163 callbacks added to index
[Info  - 17:34:03] [ElixirLS WorkspaceSymbols] 387 modules added to index
[Info  - 17:34:04] [ElixirLS WorkspaceSymbols] 557 types added to index
[Info  - 17:34:07] [ElixirLS WorkspaceSymbols] 7189 functions added to index
```

To reproduce:

- delete .elixir_ls directory
- update dependencies 
- start vscode / elixirls

### Expected behavior

still show spec suggestions and function docs. 
We noticed that the output doesn't continue with (copied from working state)

```
[Info  - 18:14:40] [ElixirLS Dialyzer] Found 1183 changed files in 1578 milliseconds
[Info  - 18:14:48] [ElixirLS Dialyzer] Analyzing 1183 modules: .......
```

**Comment by lukaszsamson** [comment] 2023-01-16 17:44
duplicate of https://github.com/elixir-lsp/elixir-ls/issues/779

**Closed by lukaszsamson** 2023-01-16 17:44 UTC
Labels: duplicate, wontfix, not a bug

**Comment by kevinschweikert** [comment] 2023-01-17 08:13
Sorry @lukaszsamson, i didn't find the already opened issue. Thanks for double checking!
