### ISSUE TITLE
Visual Studio Code elixir-ls debug only runs once, then crashes silently with subsequent attempts

### ISSUE THREAD

**Issue by DaleSparrow** [elixir-lsp/elixir-ls#397] opened 2020-11-06 16:37 UTC
### Environment

* Elixir & Erlang versions:  Erlang v22.3  Elixir v1.10.3 
* Operating system: Windows 10
* Editor: VS Code 
* Editor Plugin/LSP Client name: ElixirLS v0.6.1

### The problem

When I delete the elixer_ls folder and restart VS code I can click on the VScode debug button, it compiles, runs, and stops at the breakpoints. But only once. If I click on the run button again, the debugger starts (I can see the little lay, pause, and skip over buttons appear top right) then closes after 5 seconds with no warning, error, or output either in the console or the Electron debug console.

I need to delete the elixir_ls folder and restart VScode again to run the debugger.

I can, however, run mix compile and mix test from the VScode console as much as I like.

I am only a day old on the elixir train so there may be something I'm doing wrong, but the fact that it runs once tells me everything's in place.

### Troubleshooting

I have deleted the elixir_ls folder in the project, but this only permits one debug run before I need to delete and restart
I have restarted and re-installed elixer_ls plugin, it does not stop the single-debug run problem

### Logs
There is absolutely nothing in any of the consoles about a crash, or an error, or any sign that the debugger was even started.
No output on VS code or the electron debug console shows up! Super weird.

### attached files:

I can attach the project I'm trying to run but it's literally just the "mix new example" project

**Comment by lukaszsamson** [comment] 2020-11-07 11:39
Have you tried different elixir/otp combos? I'm not able to reproduce it on elixir 1.11.2, otp 23.1 on macOS

**Comment by DaleSparrow** [comment] 2020-11-07 18:57
> Have you tried different elixir/otp combos? I'm not able to reproduce it on elixir 1.11.2, otp 23.1 on macOS

I have not, I will try this as soon as I can and report back.

**Comment by pvormste** [comment] 2020-11-09 08:59
I have a similar experience on Windows 10 with Elixir 1.11.2 and otp 23.1.
When I start the "mix test" task from the launch config the debug panel appears and then disappears again and nothing happened. No `temp_beams` folder has been created in the `.elixir_ls` dir.
Tried on 2 different windows machines.
Is there a way to see some logs?

The same setup works on macOS though.

**Comment by axelson** [comment] 2020-11-14 20:15
Are there any warnings or errors printed out in the VSCode developer tools (Help->Toggle Developer Tools), or ElixirLS output (View->Output, select "ElixirLS" from the panel's dropdown)?

**Comment by lukaszsamson** [comment] 2020-11-15 14:58
I may have been able to reproduce it. The debugger rarely even starts on windows and the problem seems to be invalid cwd in which `debugger.bat` is being started. I'll create a PR soon.

**Comment by lukaszsamson** [comment] 2020-11-15 15:16
@DaleSparrow @pvormste please check if this PR https://github.com/elixir-lsp/vscode-elixir-ls/pull/154 resolves your issues

**Comment by DaleSparrow** [comment] 2020-11-16 11:18
@lukaszsamson Thank you! I have made a note to check it out  ASAP, we are fighting some other fires atm.

**Comment by lukaszsamson** [comment] 2020-12-07 09:30
Closing as https://github.com/elixir-lsp/vscode-elixir-ls/pull/154 is now merged

**Closed by lukaszsamson** 2020-12-07 09:30 UTC
Labels: waiting for information
