### ISSUE TITLE
Autocomplete oddity for functions

### ISSUE THREAD

**Issue by bcardarella** [elixir-lsp/elixir-ls#302] opened 2020-06-19 06:43 UTC
### Environment

* Elixir & Erlang versions (elixir --version): 1.10
* Operating system: OSX 10.15.4
* Editor or IDE name (e.g. Emacs/VSCode): VSCode
* LSP Client name:  ElixirLS

Example of issue:

![Jun-19-2020-02-35-35](https://user-images.githubusercontent.com/18524/85104413-8de60080-b1d6-11ea-80c3-b3a03d4d09f0.gif)

As you can see the autocomplete for functions doesn't seem to be working correctly. I am unsure if this is related to #193 but I think it should be clear that `do` would be the preferred completion in this case.

**Comment by axelson** [comment] 2020-06-21 08:20
@bcardarella there's two things related here. One is that we removed the override of `"editor.acceptSuggestionOnEnter": "on"`: https://github.com/elixir-lsp/vscode-elixir-ls/issues/52 so you could manually change that back. Also in https://github.com/elixir-lsp/elixir-ls/pull/259 (not yet released on VSCode" this behavior is improved and since the server is always returning a completion. So this behavior will be better on the next release (which should be fairly soon)

**Comment by lukaszsamson** [comment] 2020-09-30 16:19
It still doesn't work wight on current master

**Comment by axelson** [comment] 2020-09-30 18:41
Hmm, I'll have to double-check

**Comment by Hanspagh** [comment] 2020-12-22 09:27
This is fixed in the latest version for me.
`def foo do` returns no completions for me, which I assume is a reasonable behavoir

**Comment by lukaszsamson** [comment] 2021-03-29 09:56
I can confirm it's fixed now though I'm not sure by which commit.

**Comment by bcardarella** [comment] 2022-02-01 23:49
@axelson I reported in Slack but figured t is better here. This doesn't appear to be fixed. I'm on version 0.9.0 and seeing the same behavior from two years 18 months ago:
![Feb-01-2022 18-48-49](https://user-images.githubusercontent.com/18524/152070543-35f3d16a-bb6e-4657-8790-92b3caa9994d.gif)

**Comment by bcardarella** [comment] 2022-02-02 00:04
Can we just get exact matches to sort first? It seems reasonable if there is an exact match that is what the suggestion should be.

**Comment by lukaszsamson** [comment] 2022-02-16 10:50
> I haven't been able to investigate this since it re-appeared but I have a hunch that something changed on the VSCode sorting side of things. I'm fairly sure that ElixirLS is returning `do` earlier than `defmodule`.

I checked and we assign priority 0 to `do` in
https://github.com/elixir-lsp/elixir-ls/blob/58f07d87341d5dba2f77eae0f0a68af3fce57c44/apps/language_server/lib/language_server/providers/completion.ex#L154
Later we sort by priority in
https://github.com/elixir-lsp/elixir-ls/blob/58f07d87341d5dba2f77eae0f0a68af3fce57c44/apps/language_server/lib/language_server/providers/completion.ex#L866
Finally we assign `sortText` basing on the sort order in
https://github.com/elixir-lsp/elixir-ls/blob/58f07d87341d5dba2f77eae0f0a68af3fce57c44/apps/language_server/lib/language_server/providers/completion.ex#L885
For reference LSP client should sort on this property
```
	/**
	 * A string that should be used when comparing this item
	 * with other items. When `falsy` the label is used
	 * as the sort text for this item.
	 */
	sortText?: string;
```

There is alse `filterText`
```
	/**
	 * A string that should be used when filtering a set of
	 * completion items. When `falsy` the label is used as the
	 * filter text for this item.
	 */
	filterText?: string;
```
but we don't set it in that case so it defaults to label `do`

Maybe we should also use `preselect`?
```
	/**
	 * Select this item when showing.
	 *
	 * *Note* that only one completion item can be selected and that the
	 * tool / client decides which item that is. The rule is that the *first*
	 * item of those that match best is selected.
	 */
	preselect?: boolean;
```

**Closed** 2022-07-05 06:07 UTC
Labels: bug, good first issue

**Comment by sreecodeslayer** [comment] 2023-02-24 08:55
This issue seems to be happening on SublimeText as well through this [plugin](https://github.com/sublimelsp/LSP-elixir/).
Weird thing is, the second time I try the same line, "do" appears at the top of sort list, if not "defoverridable"

https://user-images.githubusercontent.com/5737888/221132546-8378916a-6977-465a-af69-d4aaf248553e.mov

**Comment by mhanberg** [comment] 2023-03-03 17:22
<img width="402" alt="image" src="https://user-images.githubusercontent.com/5523984/222786328-de69e5ef-9f4f-45c3-b008-43a26b674455.png">

Neovim
